São João de Meriti/RJ
okfn-brasil/querido-diario pull request #1011
Opened 2023-10-28 16:43 UTC by almeidadm

#### Checklist - Novo spider
- [X] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [X] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [X] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [X] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [X] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição
Construção da spider pra São João de Meriti/RJ através do portal https://transparencia.meriti.rj.gov.br/. 
Consulta mês a mês através do subdomínio _/diario_oficial_get.php_ e desconsidera os itens com código de anexo igual a 1. 
Download delay de 1.5 segundos para evitar o recebimento de error de servidor 500.
Estrutura de código similar ao encontrado para a cidade de Belford Roxo/RJ.

2023-11-29 15:02 UTC, ogecece requested changes
@almeidadm ótimo PR! Só dá pra dar uma melhorada nas requisições iniciais e corrigir umas bobagens:

2023-11-29 15:02 UTC, ogecece commented on data_collection/gazette/spiders/rj/rj_sao_joao_de_meriti.py
> +                continue
Uma dica pythonica é que a verificação pode ser feita de uma vez só:
```suggestion
            if self.end_date < gazette_date < self.start_date:
                continue
```

2023-11-29 16:57 UTC, almeidadm commented
Atualizações feitas!

2023-12-07 10:47 UTC, AlexJBSilva commented on data_collection/gazette/spiders/rj/rj_sao_joao_de_meriti.py
> +                continue
@almeidadm, você chegou e executar uma nova extração por período (`start_date` e `end_date` definidos) após essa modificação?

2023-12-11 15:02 UTC, almeidadm commented on data_collection/gazette/spiders/rj/rj_sao_joao_de_meriti.py
> +                continue
Oi, @AlexJBSilva!
Realmente não tinha testado essa solução.
Corrigi agora no último commit que realizei :)

2023-12-11 19:58 UTC, almeidadm commented on data_collection/gazette/spiders/rj/rj_sao_joao_de_meriti.py
> +                continue
Ah, ótimo! 
Realmente eu tinha ficado em dúvida se precisaria ser maior igual ou apenas maior.
Fiz as alterações e os testes, e agora parece que agora esta com o comportamento esperado!.

2024-01-22 14:21 UTC, trevineju requested changes
Show, @almeidadm. Você poderia só juntar todos os [8 commits](https://github.com/okfn-brasil/querido-diario/pull/1011/commits) em um só? 
Mesclo a PR assim que fizer esse ajuste

2024-01-22 14:23 UTC, trevineju commented
Arquivos da coleta completa de teste que executei hoje: 
[rj_meriti.csv](https://github.com/okfn-brasil/querido-diario/files/14011304/rj_meriti.csv)
[rj_meriti.txt](https://github.com/okfn-brasil/querido-diario/files/14011305/rj_meriti.txt)

2024-01-22 15:17 UTC, merged