Adiciona spider de TO Sampaio.
okfn-brasil/querido-diario pull request #1029
Opened 2023-11-05 19:05 UTC by vbmendes

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

Implementa o spider para a cidade de Sampaio/TO.
Issue: https://github.com/okfn-brasil/querido-diario/issues/1022

2023-11-23 17:40 UTC, vbmendes commented on data_collection/gazette/spiders/to/to_sampaio.py
> +
```suggestion
```

2023-11-28 21:56 UTC, vbmendes commented on data_collection/gazette/spiders/to/to_sampaio.py
> +    allowed_domains = ["sampaio.to.gov.br"]
Conferindo a [documentação do Scrapy](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.Spider.allowed_domains), o `allowed_domains` também permite requisições para os subdomínios. No nosso caso, a requisição para `diariooficial.sampaio.to.gov.br` também será permitida.

2023-11-29 15:10 UTC, ogecece requested changes
Tá 10/10 @vbmendes ! Só pequenos comentários:

2023-11-29 15:10 UTC, ogecece commented on data_collection/gazette/spiders/to/to_sampaio.py
> +            edition_number = title.re_first(r"\d+")
Duas pequenas melhorias:
- `extract_first()` está em desuso há algumas versões do Scrapy, o recomendado é substituir por `get()`
-  O Xpath pode ser simplificado pegando mais texto mas a lógica abaixo se mantendo muito parecida
```suggestion
            gazette_url = edition.css("a::attr(href)").get()
            title = edition.xpath("./td[1]/a/div//text()")
            is_extra_edition = "extra" in " ".join(title.getall()).lower()
            edition_number = title.re_first(r"\d+")
```

2023-11-29 15:10 UTC, ogecece commented on data_collection/gazette/spiders/to/to_sampaio.py
> +                callback=self.parse,
Se não quiser não precisa alterar, mas só avisando que esse callback pode ser omitido pois o callback padrão é o `parse()`.

2023-11-29 15:52 UTC, vbmendes commented on data_collection/gazette/spiders/to/to_sampaio.py
> +            edition_number = title.re_first(r"\d+")
Obrigado pelas sugestões.

2023-11-29 15:57 UTC, vbmendes commented on data_collection/gazette/spiders/to/to_sampaio.py
> +                callback=self.parse,
Não sabia disso. De qualquer forma, removi o callback aqui. Obrigado.

2023-11-29 15:58 UTC, vbmendes commented
> Tá 10/10 @vbmendes ! Só pequenos comentários:

Obrigado pela revisão @ogecece. Fiz as alterações sugeridas. Poderia revisar novamente, por favor?

2024-01-22 14:44 UTC, trevineju commented
Adicionei um ajuste no `start_date` e fiz [um squash no histórico para resumir os commits em um](https://github.com/okfn-brasil/querido-diario/pull/1029/commits/ce028287b7ca606039450e8fdfad6e203d59c1cf). 

Executei a coleta completa do raspador e tudo certo. 
[to_sampaio.csv](https://github.com/okfn-brasil/querido-diario/files/14011540/to_sampaio.csv)
[to_sampaio.txt](https://github.com/okfn-brasil/querido-diario/files/14011541/to_sampaio.txt)

2024-01-22 14:47 UTC, merged