[Issue][1008]Criado um novo spider para o novo site de São José dos Basílios-MA
okfn-brasil/querido-diario pull request #1030
Opened 2023-11-05 22:25 UTC by IgorJanuario

[Issue][1008]Criado um novo spider para o novo site de São José dos Basílios-MA

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [X] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [X] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [X] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero). **Observação: Ele deu skipped nesse cara.**
- [X] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [X] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

Foi necessário criar um novo spider. Criei baseado no doem.py
Esse spider foi criado para o site novo do São José dos Basílios-MA

2024-04-17 18:48 UTC, ogecece reviewed
@IgorJanuario, obrigado pelo PR de correção!

Executei uma raspagem completa no raspador e está funcionando.

Peguei a revisão desse PR agora e vi que tem alguns pontos de melhoria (ex: o uso de uma classe base onde não há outros exemplos do mesmo sistema e também a cobertura do sistema siganet estar completamente contida no novo raspador).

Você ainda tem interesse/disponibilidade de fazer as alterações? Se sim, aí posso fazer uma revisão completa e indicar os pontos de mudança.

2024-04-30 22:41 UTC, IgorJanuario commented
@ogecece bora.
Me explica e vamos mandar bala.

2024-05-01 20:19 UTC, ogecece requested changes
@IgorJanuario tá aí o/

2024-05-01 20:19 UTC, ogecece commented on data_collection/gazette/spiders/base/sjdbma.py
> +        date_cut = self.__format_date(date)
O código de `.__format_date()` não precisava estar em um método a parte aqui. Acaba quebrando a sequência de leitura por conta de uma linha de código

2024-05-01 20:19 UTC, ogecece commented on data_collection/gazette/spiders/base/sjdbma.py
> +            date_cut, date_formats=["%d - %B - %Y"], languages=["pt"]
O formato de `date_formats` só é válido para datas após 25/07/2023 e omitir esse argumento não está afetando o parsing de datas. Sugiro remover esse argumento

2024-05-01 20:19 UTC, ogecece commented on data_collection/gazette/spiders/base/sjdbma.py
> +        return self.__cut_edition_number(text_edition)
Sugiro manter o código de `.__cut_edition_number()` em `.get_edition_number()` mesmo. São poucas linhas de código pra quebrar a leitura. E o seu código já está seguindo uma estrutura que me lembra "page object", que na minha visão já está bem organizado demais.

2024-05-01 20:19 UTC, ogecece commented on data_collection/gazette/spiders/base/sjdbma.py
> +            )
Notei que `file_url` é na verdade a URL para uma página intermediária ([exemplo](https://diariooficial.saojosedosbasilios.ma.gov.br/diariooficial/edicao/1227.pdf#page=)) e não para o arquivo de diário. Seria necessário mais um método de parsing para então encontrar o link do diário (parece que o botão "Baixar PDF" entrega) e então criar o item `Gazette`.

2024-09-07 23:53 UTC, ogecece commented
@IgorJanuario essa correção foi priorizada daí pedi pro @victorfernandesraton endereçar ela, beleza? Ele pegou a partir de onde vc parou e continuou em #1264.

Esse desencontro do tempo de revisão acabou provavelmente te pegando num período de pouca disponibilidade e tá tudo bem. Muito obrigado por ter puxado essa correção!

Vou dar prioridade a revisão do outro PR e fechar esse aqui.

E se quiser pegar outras issues do QD, fica à vontade!

2024-09-07 23:53 UTC, closed without merging