Adiciona link para as metas no CONTRIBUTING.md (Issue #499)
okfn-brasil/querido-diario pull request #1080
Opened 2024-02-25 10:50 UTC by BrenoFariasdaSilva

Este Pull Request introduz uma melhoria no arquivo CONTRIBUTING.md, adicionando uma seção que vincula diretamente às metas do repositório no GitHub. A inclusão deste link visa tornar as metas mais acessíveis e visíveis para os contribuidores, incentivando uma maior participação alinhada com os objetivos do projeto Querido Diário.

### Mudanças Propostas

- Adicionada a seção "Metas do Repositório" em CONTRIBUTING.md.
- Incluído link para as [metas do repositório](https://github.com/okfn-brasil/querido-diario/milestones) que direciona os contribuidores para uma visão clara dos objetivos atuais do projeto.

Closes #499.

2024-03-26 18:06 UTC, trevineju requested changes

2024-03-26 18:06 UTC, trevineju commented on docs/CONTRIBUTING.md
> +  - [Formação automática de código](#formação-automática-de-código)
```suggestion
  - [Formatação automática de código](#formação-automática-de-código)
```

É formatação mesmo, @BrenoFariasdaSilva. Essa seção é sobre um recurso que temos que formata o código das pessoas automaticamente ao enviar uma PR, para adequar o padrão de código ao projeto.

2024-03-26 18:06 UTC, trevineju commented on docs/CONTRIBUTING.md
> +Para garantir que nossos esforços estejam alinhados e focados em objetivos claros, definimos metas para o desenvolvimento e expansão do projeto. Estas metas são revisadas e atualizadas regularmente,
Ficou excelente, @BrenoFariasdaSilva! Ajustei só pra ficar neutro de gênero.

```suggestion
Para garantir que nossos esforços estejam alinhados e focados em objetivos claros, definimos metas para o desenvolvimento e expansão do projeto. Estas metas são revisadas e atualizadas regularmente, refletindo as prioridades e os desafios que enfrentamos. Convidamos as pessoas contribuidoras a se familiarizarem com estas metas, disponíveis em nosso [Quadro de Metas](https://github.com/okfn-brasil/querido-diario/milestones). Sua contribuição pode ser ainda mais valiosa quando alinhada com estas direções.
```

2024-03-26 18:08 UTC, trevineju approved these changes
Obrigada pela PR, @BrenoFariasdaSilva! (e pela paciência em aguardar) 

Adicionei dois ajustes pequenos que você pode ver no histórico da conversa. Como é simples, já aceitei o ajuste e vou mesclar a PR. 

<img src="https://media1.giphy.com/media/R6gvnAxj2ISzJdbA63/giphy-downsized-medium.gif"/>

2024-03-26 18:13 UTC, merged

2024-03-27 13:19 UTC, BrenoFariasdaSilva commented
Ok, muito obrigado!