#1221 Adiciona base para o sistema modernizacao
okfn-brasil/querido-diario pull request #1236
Opened 2024-07-31 13:14 UTC by slfabio

**AO ABRIR** uma *Pull Request* de um novo raspador (*spider*), marque com um `X` cada um dos items da checklist abaixo. Caso algum item não seja marcado, JUSTIFIQUE o motivo.

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [x] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [ ] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [x] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [ ] Não utilizo `custom_settings` em meu raspador.
**Foi necessário incluir DOWNLOAD_DELAY para alguns municípios para reduzir a quantidade de "retry/reason_count/500 Internal Server Error", que ocasionava erros para baixar alguns itens.**

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

[LOG - 1221.zip](https://github.com/user-attachments/files/16442279/LOG.-.1221.zip)

#### Descrição

#1221 Cria base para o sistema modernização. 
- Adiciona BaseModernizacaoSpider;
- Adiciona 4 novos spiders: rj_miguel_pereira; rj_quatis; rj_queimados e rj_sao_pedro_da_aldeia;
- Atualiza 2 spiders de municípios que utilizam o mesmo sistema: rj_belford_roxo; rj_sao_joao_de_meriti; e
- Atualiza a URL_BASE de rj_belford_roxo que estava desatualizada.

2024-07-31 22:32 UTC, trevineju requested changes
boa, @slfabio! obrigada pela contribuição 

Deixei algumas sugestões para você ver. Se concordar pode aceitar ou se quiser discordar e quiser debater mais, responder. 

Nesse tipo de raspador, a questão maior é a abstração. Até que ponto dá pra abstrair/generalizar coisas pra deixar na classe-mãe, simplificando os raspadores dos municípios. Os feedbacks orbitaram essa lógica: enxugar a classe filha e deixar a complexidade na mãe.

Tenho mais duas questões: 
1. Entendi que partiu dos códigos prontos para reorganizar as classes, mas nisso, o método [`start_requests()` de rj_belford_roxo.py](https://github.com/okfn-brasil/querido-diario/blob/f85325088e4f648a60ccebc28d920b5e305dce87/data_collection/gazette/spiders/rj/rj_belford_roxo.py#L18) não foi aproveitado. Como ele fazia controle de data desde a requisição sendo feita parece um bom método para usar. Você identificou algo para não reaproveitá-lo? 

2. Fiquei pensando em reduzir a `base_url` também... 
Todas elas são `https://<dominio_do_municipio>/<codigo_ver>/WEB-ObterAnexo.rule?sys=LAI&codigo={ATTACHMENT_CODE}` 

O `dominio_do_municipio` dá para pegar a partir de `start_urls`. A única coisa que muda é esse `codigo_ver`. A maior parte dos casos é `ver20230623`, só São Pedro da Aldeia é `ver20240713`. Daria pra gente assumir que é `ver20230623` por padrão e, quando necessário, o raspador específico sobreescreve o atributo de classe. Algo como... 

~~~py
class BaseModernizacaoSpider(BaseGazetteSpider):
    ver_subpath = "ver20230623"
    
    def parse(self, response):
    # ...
    # continua até a linha 17
    gazette_url = f"{dominio}/{self.ver_subpath}/WEB-ObterAnexo.rule?sys=LAI&codigo={gazette_code}"
 ~~~
 
 Aí, todos os raspadores da PR não precisarão de `ver_subpath` por usarem que está configurado por default, só São Pedro da Aldeia que terá uma linha para sobreescrever o atributo
 
 ~~~py
class RjSaoPedroDaAldeiaSpider(BaseModernizacaoSpider):
    TERRITORY_ID = "3305208"
    # ... 
    ver_subpath = "ver20240713"
~~~

O que acha?

2024-08-01 02:18 UTC, slfabio commented
Boa noite @trevineju , muito obrigado pelas sugestões. Melhoraram bastante o código, aceitei todas.

Sobre o strarts_requests() de rj_belford_roxo, a requisição para a URL mapeada em starts_url sem o parâmetro "mesano" já retorna um JSON com todas as edições existentes, por isso não vi necessidade de fazer uma requisição para cada mês.
Você acha que a estratégia acessando mês a mês tem algum benefício em relação à performance ou outro motivo?

Sobre a redução da base_url acho uma ideia, vou fazer esse ajuste.

2024-08-01 10:19 UTC, slfabio commented
Bom dia @trevineju,
agora que eu me atentei que a raspagem completa só ocorre na primeira execução e que a forma que eu implementei vai iterar sobre a lista completa sem necessidade nas execuções parciais.
Vou retornar com a estratégia de consulta mês a mês.
Obrigado pela ajuda

2024-08-01 13:56 UTC, trevineju commented
> Bom dia @trevineju, agora que eu me atentei que a raspagem completa só ocorre na primeira execução e que a forma que eu implementei vai iterar sobre a lista completa de DOs sem necessidade nas execuções parciais. Vou retornar com a estratégia de consulta mês a mês a partir da data inicial. Obrigado pela ajuda

Isso! Boa

2024-08-01 21:48 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_belford_roxo.py
> +    custom_settings = {"DOWNLOAD_DELAY": 0.25, "RANDOMIZE_DOWNLOAD_DELAY": True}
Sugestão implementada

2024-08-01 21:49 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_belford_roxo.py
> +    custom_settings = {"DOWNLOAD_DELAY": 0.25, "RANDOMIZE_DOWNLOAD_DELAY": True}
Sugestão implementada

2024-08-01 23:05 UTC, slfabio commented
Boa noite @trevineju,

retornei com o filtro por data e implementei sua sugestão para enxugar os spiders dos municípios.
Os testes após as correções estão em anexo.
[LOG.zip](https://github.com/user-attachments/files/16462590/LOG.zip)

2024-08-05 13:19 UTC, slfabio commented
[LOG_mesquita.zip](https://github.com/user-attachments/files/16496286/LOG_mesquita.zip)
Log dos testes de rj_mesquita

2024-08-05 15:13 UTC, trevineju commented
@slfabio, obrigada pelos ajustes!! 

Adicionei mais algumas coisinhas. Como foi um erro meu, de deixar passar na primeira revisão, finalizei por aqui. Além disso, atualizei o histórico desta branch com a main. 

1. No campo `edition_number` é esperado apenas número mesmo (no máximo número com alguma letra, como "485A"). Nos LOGs que anexou, o campo está preenchido com textos diversos. 
Adicionei um trecho de código com uma regex para capturar o número e se não tiver deixa vazio. 

2. As responses 302 e 500. 

- O código 302 significa redirecionamento. Exemplo:
> Redirecting (302) to <GET https://transparencia.mesquita.rj.gov.br/ver20240713/WEB-ObterAnexo.rule?sys=LAI&codigo=12290> from <GET https://transparencia.mesquita.rj.gov.br/ver20230623/WEB-ObterAnexo.rule?sys=LAI&codigo=12290>` 

Isso só foi indício que o `ver_subpath` estava errado em dois raspadores.

- O código 500 você já deixou explicado ao abrir a PR, mas precisamos que não tenha nenhum. Aqui não tem segredo, é literalmente ficar chutando opções de `custom_settings` até o raspador exigir menos do site publicador. 

Com seus logs, temos os seguintes valores de presença de status 500:
![image](https://github.com/user-attachments/assets/798b5b75-69fc-4b3b-a756-30d537a10c33)

Além do delay, diminui a quantidade de requisições paralelas feitas (concorrência). Por padrão são 8. Com as settings que adicionei na PR, não teve mais código 500: 
![image](https://github.com/user-attachments/assets/9af50830-07d2-4160-82a9-fec88f8ac916)

Porém, como a coleta completa demora muito, testei com um intervalo de alguns meses. Como os 500 sumiram, já pareceu um bom sinal, agora estou rodando a completa. 

Deixo os logs com evidências da modificação 1 e da 2.
[coletas_por_intervalo.zip](https://github.com/user-attachments/files/16499495/coletas_por_intervalo.zip)

Assim que acabar, trago novidades. Correndo tudo bem, acredito que a PR está pronta. É bom que também te dá um tempo de dar uma olhada e comentar algo que ainda queira

2024-08-05 21:04 UTC, slfabio commented
Obrigado, @trevineju,
nas próximas vou me atentar aos status das responses, eu tinha focado apenas nos que geraram erros.
Também entendi a questão do nº da edição.
Vou passar essas orientações para o pessoal que vai implementar os próximos spiders.

Minha única dúvida é quanto à inclusão das novas prefeituras na plataforma: depois que o código é integrado os Diários das novas prefeituras já ficam disponíveis? Pergunto, pois as prefeituras que você incluiu semana passada ainda não aprecem com nível 3 no site do Querido Diário.

2024-08-05 22:34 UTC, trevineju commented
> Obrigado, @trevineju, nas próximas vou me atentar aos status das responses, eu tinha focado apenas nos que geraram erros. 

Realmente, cada requisição é tentada 3 vezes, então não é um problema aparecer algumas responses 500, contanto que em outras tentativas seja coletado (= não ter `failed 3 times` no log). Mas como eram bastantes e é uma base que vai ser usada por não sabemos quantos municípios ao todo é melhor exigir menos

> Também entendi a questão do nº da edição. Vou passar essas orientações para o pessoal que vai implementar os próximos spiders.

Obrigada pelo cuidado! 

> Minha única dúvida é quanto à inclusão das novas prefeituras na plataforma: depois que o código é integrado os Diários das novas prefeituras já ficam disponíveis? Pergunto, pois as prefeituras que você incluiu semana passada ainda não aprecem com nível 3 no site do Querido Diário.

É que o site do QD ainda é um pouco limitado e demanda atualização manual pros níveis -- coisa que ainda não parei pra fazer e estava esperando essa PR terminar pra atualizar tudo de uma vez só. Estamos planejando algumas melhorias e automatizar isso será uma delas. Mas já está pesquisável, sim: https://queridodiario.ok.org.br/pesquisa?city=3305158&city=3304151&city=3301876&city=3300233&since=2024-07-01&until=2024-08-05&sort_by=descending_date

No geral, no dia seguinte já está disponível.

2024-08-05 23:02 UTC, slfabio commented
> É que o site do QD ainda é um pouco limitado e demanda atualização manual pros níveis -- coisa que ainda não parei pra fazer e estava esperando essa PR terminar pra atualizar tudo de uma vez só. Estamos planejando algumas melhorias e automatizar isso será uma delas. Mas já está pesquisável, sim: https://queridodiario.ok.org.br/pesquisa?city=3305158&city=3304151&city=3301876&city=3300233&since=2024-07-01&until=2024-08-05&sort_by=descending_date
> 
> No geral, no dia seguinte já está disponível.

Perfeito. Muito obrigado!

2024-08-05 23:14 UTC, trevineju commented
E é isso, aí! Tudo certo com as coletas finais 

[coletas_completas.zip](https://github.com/user-attachments/files/16503498/coletas_completas.zip)

2024-08-05 23:14 UTC, trevineju approved these changes
Obrigada pela contribuição!

2024-08-05 23:19 UTC, merged