Novo Spider - Angra dos Reis/RJ
okfn-brasil/querido-diario pull request #1250
Opened 2024-08-10 20:10 UTC by slfabio

**AO ABRIR** uma *Pull Request* de um novo raspador (*spider*), marque com um `X` cada um dos items da checklist abaixo. Caso algum item não seja marcado, JUSTIFIQUE o motivo.

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [x] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [ ] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [x] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
[ultima.log](https://github.com/user-attachments/files/16570770/ultima.log)

- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
[intervalo.csv](https://github.com/user-attachments/files/16570771/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/16570772/intervalo.log)

- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.
[completa.csv](https://github.com/user-attachments/files/16570774/completa.csv)
[completa.log](https://github.com/user-attachments/files/16570775/completa.log)

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Cria spider para Angra dos Reis/RJ, conforme issue #1191

2024-09-04 17:45 UTC, ogecece requested changes
@slfabio o raspador tá bem bão, mas tenho alguns pontos pra trazer aqui:

2024-09-04 17:45 UTC, ogecece commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +        for year in range(end_year, (start_year - 1), -1):
Essa ordem não importa tanto pois as requisições serão processadas de forma assíncrona. Sugiro deixar em ordem ascendente pra ficar uma besteira mais fácil de ler :)
```suggestion
        for year in range(start_year, end_year + 1):
```

2024-09-04 17:45 UTC, ogecece commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +        for tr in response.xpath("//tr")[1:]:
Pra não ficar muito sujeito a mudanças no layout do site introduzindo uma tabela indesejada, sugiro restringir um pouco mais onde estamos esperando os `tr` aparecerem
```suggestion
        for tr in response.xpath("//article//tr")[1:]:
```

2024-09-04 17:45 UTC, ogecece commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +            is_extra_edition = "EXTRA" in raw_gazette_edition.upper()
Aqui dá pra fazer uso de `.re_first()` e simplificar um pouco o uso de match. E também usar o fato do `.get()` sempre pegar o texto do primeiro elemento de uma `SelectorList`.
```suggestion
            raw_gazette_edition = tr.xpath("./td/text()")
            gazette_edition_number = raw_gazette_edition.re_first(r"\d+") or ""
            is_extra_edition = "EXTRA" in raw_gazette_edition.get().upper()
```

2024-09-04 17:45 UTC, ogecece commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +            gazette_url = response.urljoin(url_subdir)
Tendo como exemplo 2006-12-08, a url também pode indicar que a edição é extra, mesmo que a tabela não indique

2024-09-04 17:45 UTC, ogecece commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +                power="executive_legislative",
Conseguisse achar alguma edição com atos do legislativo? Só encontrei do executivo aqui

2024-09-05 14:53 UTC, ogecece commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +                power="executive_legislative",
Nossa... beleza!

2024-09-05 17:35 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +        for year in range(end_year, (start_year - 1), -1):
Sugestão aplicada.

2024-09-05 17:36 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +        for tr in response.xpath("//tr")[1:]:
Sugestão aplicada.

2024-09-05 17:36 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +            is_extra_edition = "EXTRA" in raw_gazette_edition.upper()
Sugestão aplicada.

2024-09-05 17:37 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
> +            gazette_url = response.urljoin(url_subdir)
Alterei para validar se a edição é extra também pela URL.

Obrigado pelas dicas, @ogecece!

2024-09-05 19:02 UTC, ogecece approved these changes
Tudo funcionando, tá :100:!

2024-09-05 19:08 UTC, merged