spider: sp_alvares_florence
okfn-brasil/querido-diario pull request #1255
Opened 2024-08-27 17:13 UTC by josehenriqueroveda

**AO ABRIR** uma *Pull Request* de um novo raspador (*spider*), marque com um `X` cada um dos items da checklist abaixo. Caso algum item não seja marcado, JUSTIFIQUE o motivo.

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [X] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [X] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [X] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [X] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [X] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [X] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [X] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [X] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [X] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.
> Arquivos de saída de testes foram ignorados no commit.

#### Verificações
- [X] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [X] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [X] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Adicionado o spider para o município Alvares Florence - SP.

2024-08-27 19:37 UTC, trevineju commented
Oi, @josehenriqueroveda! Obrigada pela contribuição 

Quanto ao comentário que deixou...
> Arquivos de saída de testes foram ignorados no commit.

Não era para adicionar os arquivos de saída ao código da PR mesmo, mas sim aqui pela interface do GitHub.

2024-08-27 19:39 UTC, trevineju requested changes

2024-08-27 19:39 UTC, trevineju commented on data_collection/gazette/spiders/sp/sp_alvares_florence.py
> +class SpCajuruSpider(BaseInstarSpider):
```suggestion
class SpAlvaresFlorenceSpider(BaseInstarSpider):
```

2024-08-28 14:23 UTC, josehenriqueroveda reviewed
Corrigido o nome da classe: SpAlvaresFlorenceSpider

2024-09-04 17:43 UTC, trevineju commented
oi, @josehenriqueroveda

Nessa seção era esperado que os testes fossem anexados ao GitHub para que pudesse ser feita a revisão mais rápida

> #### Testes
> * [x]  Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
> * [x]  Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
> * [x]  Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.


Mas executei aqui e confirmei que está tudo ok. Segue os arquivos de saída: 
[completa_sp_alvares_florence.log](https://github.com/user-attachments/files/16874770/completa_sp_alvares_florence.log)
[completa_sp_alvares_florence.csv](https://github.com/user-attachments/files/16874772/completa_sp_alvares_florence.csv)
[intervalo_sp_alvares_florence.log](https://github.com/user-attachments/files/16874773/intervalo_sp_alvares_florence.log)
[intervalo_sp_alvares_florence.csv](https://github.com/user-attachments/files/16874774/intervalo_sp_alvares_florence.csv)

2024-09-04 17:43 UTC, trevineju approved these changes
Obrigada pela contribuição

2024-09-04 17:44 UTC, merged