Feature - Novo spider para Arraial do Cabo - RJ [Fixes #1261]
okfn-brasil/querido-diario pull request #1275
Opened 2024-09-21 03:09 UTC by jjpaulo2

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [x] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [ ] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [x] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Novo spider customizado para Arraial do Cabo, conforme #1261. Eu mudei a data de início pois o registro mais antigo que eu consegui encontrar manualmente no site foi em `07/05/2019`.

## Anexos

#### Coleta última edição

```
scrapy crawl rj_arraial_do_cabo -a start_date=2024-09-20 -s LOG_FILE=rj_arraial_do_cabo.log -o rj_arraial_do_cabo.csv
```

- [rj_arraial_do_cabo.csv](https://github.com/user-attachments/files/17082584/rj_arraial_do_cabo.csv)
- [rj_arraial_do_cabo.log](https://github.com/user-attachments/files/17082585/rj_arraial_do_cabo.log)

#### Coleta intervalo

```
scrapy crawl rj_arraial_do_cabo -a start_date=2024-09-01 -a end_date=2024-09-20 -s LOG_FILE=rj_arraial_do_cabo.log -o rj_arraial_do_cabo.csv
```

- [rj_arraial_do_cabo.csv](https://github.com/user-attachments/files/17082599/rj_arraial_do_cabo.csv)
- [rj_arraial_do_cabo.log](https://github.com/user-attachments/files/17082600/rj_arraial_do_cabo.log)

#### Coleta completa

```
scrapy crawl rj_arraial_do_cabo -s LOG_FILE=rj_arraial_do_cabo.log -o rj_arraial_do_cabo.csv
```

- [rj_arraial_do_cabo.csv](https://github.com/user-attachments/files/17082562/rj_arraial_do_cabo.csv)
- [rj_arraial_do_cabo.log](https://github.com/user-attachments/files/17082563/rj_arraial_do_cabo.log)

2024-09-22 13:47 UTC, ayharano commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +    start_date = date(2019, 5, 7)
Iterando com o site passado, pude ver que o primeiro diário disponível seria 11 de abril de 2019

![image](https://github.com/user-attachments/assets/6a8d3308-ff65-4985-8091-5442f35d2976)

Como você determinou a data de 7 de maio de 2019?

Apesar da busca, o de maio é o primeiro disponível?

2024-09-22 18:55 UTC, jjpaulo2 commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +    start_date = date(2019, 5, 7)
De fato! Peguei essa data "no olho" kkkk
Rodei um scrapping completo, e de fato a data mais antiga é `2019-04-11`.

![image](https://github.com/user-attachments/assets/d217fbc3-337c-4dcf-a2a4-451cbd31d9c2)

2024-09-22 19:01 UTC, jjpaulo2 commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +    start_date = date(2019, 5, 7)
Eu também tinha adicionado um trecho de código para parar a paginação caso não houvesse mais necessidade de rodar o scrapping, meu acabei removendo esse trecho.

```python
if publish_date < self.start_date:
    return
```

Percebi que as últimas páginas não estão ordenadas. Isso iria fazer o spider não capturar todos os registros necessários.

2024-09-23 16:51 UTC, trevineju commented
@jjpaulo2, só uma dica: pra vincular a PR à issue que está resolvendo, a mensagem "Fixes #1261" precisa estar no corpo da PR, no título não funciona. (não me pergunte pq hahahaha)
 
vinculei manualmente agora

2024-09-23 17:53 UTC, trevineju commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +class RjArraialdoCabopider(BaseGazetteSpider):
```suggestion
class RjArraialdoCaboSpider(BaseGazetteSpider):
```

2024-09-23 19:25 UTC, trevineju requested changes
boa, @jjpaulo2 e @ayharano! 

Tava só dando uma olhada na PR, quando lembrei que esse era o caso que estávamos discutindo em #1261 que talvez nem desse pra integrar. Mas parece que a prefeitura corrigiu o site, ne, JP? 

Como parei pra olhar, acabei revisando :see_no_evil:

Os logs parecem ótimos (uma tistreza aqueles milhares de redirecionamentos - `response_status_count/302': 1116` - na coleta completa, mas não tem jeito mesmo, é o site que é feio assim :crying_cat_face:). Só endereçarmos alguns ajustes no código que, por mim, é isso! 

Quer complementar com algo, @ayharano?

2024-09-23 19:25 UTC, trevineju commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +            yield Request(next_page.extract_first(), callback=self.parse)
Pode omitir pq o `parse` já é o callback padrão do Scrapy.

```suggestion
            yield Request(next_page.get(), callback=self.parse)
```
Aproveitando e já deixando outra troca do alias

2024-09-23 19:30 UTC, jjpaulo2 commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +    def parse(self, response: HtmlResponse):
Aqui foi só pelo typing mesmo @trevineju. Vou remover pra manter o padrão do repositório.

2024-09-23 19:36 UTC, trevineju commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +    def parse(self, response: HtmlResponse):
bele! Lembra de tirar o import também!

2024-09-23 19:37 UTC, jjpaulo2 commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +                territory_id=self.TERRITORY_ID,
@trevineju eu inclui aqui pq achei esse campo [aqui](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/items.py#L13). Ele não é mais usado?

2024-09-23 19:40 UTC, jjpaulo2 commented
@trevineju ajustes feitos.

Seguem os arquivos de coleta completa após os ajustes:
- [rj_arraial_do_cabo.csv](https://github.com/user-attachments/files/17103309/rj_arraial_do_cabo.csv)
- [rj_arraial_do_cabo.log](https://github.com/user-attachments/files/17103310/rj_arraial_do_cabo.log)

2024-09-23 19:42 UTC, trevineju commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +    start_date = date(2019, 5, 7)
> Percebi que as últimas páginas não estão ordenadas. Isso iria fazer o spider não capturar todos os registros necessários.

Isso aqui é uma boa discussão. Acho que elas estão ordenadas por uma ordenação que não está transparente pra gente. Já vi outros casos que, por erro humano na hora de adicionar a nova edição, o diário mais novo ficou na última página também. 

Como as linhas 25 e 26 fazem filtro, imagino que tenha voltado atrás depois dessa conversa e colocado -- até pq a coleta da última edição e a por intervalo não funcionam sem. 

Acho que podemos abrir uma issue para conversar sobre melhorar nossas rotinas "coleta de segurança", o que acham?

2024-09-23 20:11 UTC, trevineju commented
Obrigada! Por mim, tá aprovado. Só aguardando Harano comentar também

2024-09-25 14:55 UTC, jjpaulo2 commented on data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
> +    start_date = date(2019, 5, 7)
O único filtro que tá sendo feito hoje é pra validar se o registro está dentro do intervalo de datas que estamos olhando. Mas mesmo que a gente queira pegar apenas o registro de um dia específico, o spider vai olhar todas as páginas.

Essa questão da ordenação ajudaria a gente a identificar caso não fosse mais necessário raspar informações. O que ajudaria a diminuir a quantidade de requisições pro site. Por exemplo, se eu vou raspar até o dia X, e eu sei que nessa página eu achei o último registro desse dia, eu posso encerrar o scrapping ali mesmo.

2024-10-16 18:50 UTC, jjpaulo2 commented
Oi @ayharano. Você vê mais algum problema? 🫣

2025-01-15 00:33 UTC, trevineju commented
Como resolve um problema de manutenção, coisa prioritária, estou acolhendo a PR aprovada.

Por via das dúvidas, executei de novo para garantir que tá funcionando por já fazer uns meses e o site poder ser atualizado, e tudo certo ( [rj_arraial_do_cabo_periodo_3meses.log](https://github.com/user-attachments/files/18417469/rj_arraial_do_cabo_periodo_3meses.log) | [rj_arraial_do_cabo_periodo_3meses.csv](https://github.com/user-attachments/files/18417470/rj_arraial_do_cabo_periodo_3meses.csv) )

2025-01-15 00:33 UTC, trevineju approved these changes

2025-01-15 00:34 UTC, merged