Adiciona novos 8 raspadores
okfn-brasil/querido-diario pull request #1281
Opened 2024-09-25 13:21 UTC by trevineju

As spiders adicionadas nesta PR foram criadas com um *script* criador de código, por isso toda essa PR deve ser revisada em todos os detalhes e também ser testada. 

Fica a cargo da pessoa revisora verificar a lista de [validações para contribuições](https://github.com/okfn-brasil/querido-diario/blob/main/.github/pull_request_template.md).

2024-09-25 18:39 UTC, jjpaulo2 commented
Farei a revisão 😉

2024-09-26 11:55 UTC, trevineju commented
essa aqui o @jreagle falou que faria em https://github.com/okfn-brasil/querido-diario/issues/1088#issuecomment-2374739071

2024-09-26 12:16 UTC, jjpaulo2 commented
Aaah, blz!

2024-09-27 17:20 UTC, jreagle commented
> essa aqui o @jreagle falou que faria em [#1088 (comment)](https://github.com/okfn-brasil/querido-diario/issues/1088#issuecomment-2374739071)

Obrigado p/ preferência! 😜

2024-10-02 23:58 UTC, jreagle approved these changes
# Feedback Review

Conforme registrado trilha, os raspadores replicados de "mg_carmo_do_rio_claro" e "mg_juatuba" já fazem parte da branch principa, portanto, devem ser removidos da pull.

De acordo com [territories.csv](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/resources/territories.csv#10) existe o município de Candeias - BA (2906501), que não consta da base de produção do QD atualmente e, curiosamente, publica seus diários pelo sistema BaseInstar!  Eu cheguei até fazer os testes de coleta com sucesso com base no [ba_candeias.py](https://github.com/okfn-brasil/querido-diario/blob/be5a58e2e4ea3c5e9faa97bd09cd002d6dd2ce96/data_collection/gazette/spiders/ba/ba_candeias.py)! Só pra registro mesmo! 

Em relação aos demais arquivos, após verificar a lista de [validações para contribuições](https://github.com/okfn-brasil/querido-diario/blob/main/.github/pull_request_template.md) recomendada pela @trevineju e não encontrar erros ou alertas relevantes nos logs saída, considero que as mudanças podem ser aprovadas e integradas ao branch principal sem maiores problemas.

2024-10-02 23:58 UTC, jreagle commented on data_collection/gazette/spiders/mt/mt_cotriguacu.py
#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [x] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [ ] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Adiciona raspador de município replicado (mg_cotrigaguacu) a partir do padrão BaseINSTAR #1088

#### Logs (Tests)

[mt_cotriguacu_between_2023-11-17_2024-09-30.log](https://github.com/user-attachments/files/17236916/mt_cotriguacu_between_2023-11-17_2024-09-30.log)
[mt_cotriguacu_full_2024-09-30.csv](https://github.com/user-attachments/files/17236917/mt_cotriguacu_full_2024-09-30.csv)
[mt_cotriguacu_full_2024-09-30.log](https://github.com/user-attachments/files/17236918/mt_cotriguacu_full_2024-09-30.log)
[mt_cotriguacu_last_2024-09-30.csv](https://github.com/user-attachments/files/17236919/mt_cotriguacu_last_2024-09-30.csv)
[mt_cotriguacu_last_2024-09-30.log](https://github.com/user-attachments/files/17236921/mt_cotriguacu_last_2024-09-30.log)
[mt_cotriguacu_between_2023-11-17_2024-09-30.csv](https://github.com/user-attachments/files/17236922/mt_cotriguacu_between_2023-11-17_2024-09-30.csv)
[mt_cotriguacu_between_2023-11-17_2024-09-30.csv](https://github.com/user-attachments/files/17236922/mt_cotriguacu_between_2023-11-17_2024-09-30.csv)

2024-10-02 23:58 UTC, jreagle commented on data_collection/gazette/spiders/pr/pr_santo_antonio_do_paraiso.py
#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [x] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [ ] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Adiciona raspador de município replicado (**pr_santo_antonio_do_paraiso**) a partir do padrão [BaseINSTAR](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/instar.py)

#### Logs (Tests)

[pr_santo_antonio_do_paraiso_full_2024-10-02.csv](https://github.com/user-attachments/files/17237319/pr_santo_antonio_do_paraiso_full_2024-10-02.csv)
[pr_santo_antonio_do_paraiso_full_2024-10-02.log](https://github.com/user-attachments/files/17237320/pr_santo_antonio_do_paraiso_full_2024-10-02.log)
[pr_santo_antonio_do_paraiso_last_2024-10-02.csv](https://github.com/user-attachments/files/17237321/pr_santo_antonio_do_paraiso_last_2024-10-02.csv)
[pr_santo_antonio_do_paraiso_last_2024-10-02.log](https://github.com/user-attachments/files/17237322/pr_santo_antonio_do_paraiso_last_2024-10-02.log)
[pr_santo_antonio_do_paraiso_between_2012-12-27_2013-01-26.csv](https://github.com/user-attachments/files/17237323/pr_santo_antonio_do_paraiso_between_2012-12-27_2013-01-26.csv)
[pr_santo_antonio_do_paraiso_between_2012-12-27_2013-01-26.log](https://github.com/user-attachments/files/17237324/pr_santo_antonio_do_paraiso_between_2012-12-27_2013-01-26.log)

2024-10-02 23:58 UTC, jreagle commented on data_collection/gazette/spiders/sp/sp_iracemapolis.py
#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [x] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [ ] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Adiciona raspador de município replicado (**sp_iracemapolis**) a partir do padrão [BaseINSTAR](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/instar.py)

#### Logs (Tests)


[sp_iracemapolis_full_2024-10-02.csv](https://github.com/user-attachments/files/17237396/sp_iracemapolis_full_2024-10-02.csv)
[sp_iracemapolis_full_2024-10-02.log](https://github.com/user-attachments/files/17237398/sp_iracemapolis_full_2024-10-02.log)
[sp_iracemapolis_last_2024-10-02.csv](https://github.com/user-attachments/files/17237399/sp_iracemapolis_last_2024-10-02.csv)
[sp_iracemapolis_last_2024-10-02.log](https://github.com/user-attachments/files/17237400/sp_iracemapolis_last_2024-10-02.log)
[sp_iracemapolis_between_2017-01-02_2024-10-02.csv](https://github.com/user-attachments/files/17237401/sp_iracemapolis_between_2017-01-02_2024-10-02.csv)
[sp_iracemapolis_between_2017-01-02_2024-10-02.log](https://github.com/user-attachments/files/17237402/sp_iracemapolis_between_2017-01-02_2024-10-02.log)

2024-10-02 23:58 UTC, jreagle commented on data_collection/gazette/spiders/sp/sp_itaporanga.py
#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [x] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [ ] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Adiciona raspador de município replicado (**sp_itaporanga**) a partir do padrão [BaseINSTAR](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/instar.py)

#### Logs (Tests)

[sp_itaporanga_between_2009-04-16_2009-05-16.csv](https://github.com/user-attachments/files/17237424/sp_itaporanga_between_2009-04-16_2009-05-16.csv)
[sp_itaporanga_between_2009-04-16_2009-05-16.log](https://github.com/user-attachments/files/17237426/sp_itaporanga_between_2009-04-16_2009-05-16.log)
[sp_itaporanga_full_2024-10-02.csv](https://github.com/user-attachments/files/17237427/sp_itaporanga_full_2024-10-02.csv)
[sp_itaporanga_full_2024-10-02.log](https://github.com/user-attachments/files/17237428/sp_itaporanga_full_2024-10-02.log)
[sp_itaporanga_last_2024-10-02.csv](https://github.com/user-attachments/files/17237429/sp_itaporanga_last_2024-10-02.csv)
[sp_itaporanga_last_2024-10-02.log](https://github.com/user-attachments/files/17237430/sp_itaporanga_last_2024-10-02.log)

2024-10-02 23:58 UTC, jreagle commented on data_collection/gazette/spiders/sp/sp_potirendaba.py
#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [x] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [ ] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

Adiciona raspador de município replicado (**sp_potirendaba**) a partir do padrão [BaseINSTAR](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/instar.py)

#### Logs (Tests)

[sp_potirendaba_between_2024-01-21_2024-02-20.csv](https://github.com/user-attachments/files/17237434/sp_potirendaba_between_2024-01-21_2024-02-20.csv)
[sp_potirendaba_between_2024-01-21_2024-02-20.log](https://github.com/user-attachments/files/17237435/sp_potirendaba_between_2024-01-21_2024-02-20.log)
[sp_potirendaba_full_2024-10-02.csv](https://github.com/user-attachments/files/17237436/sp_potirendaba_full_2024-10-02.csv)
[sp_potirendaba_full_2024-10-02.log](https://github.com/user-attachments/files/17237437/sp_potirendaba_full_2024-10-02.log)
[sp_potirendaba_last_2024-10-01.csv](https://github.com/user-attachments/files/17237438/sp_potirendaba_last_2024-10-01.csv)
[sp_potirendaba_last_2024-10-01.log](https://github.com/user-attachments/files/17237439/sp_potirendaba_last_2024-10-01.log)

2024-10-03 22:14 UTC, trevineju commented
boa, @jreagle! 🎉🎉🎉  

Mas vou pedir pra você fazer de novo seguindo o "rito certo", tudo bem? 😊 

A opção de aprovar só é selecionada quando a PR estiver pronta mesmo. No caso, você está solicitando que se faça remoções, então tinha que escolher "request changes". Isso vai bloquear a PR de seguir em frente enquanto as mudanças pedidas não forem endereçadas. 

Aí a tarefa volta pra pessoa desenvolvedora, pra justificar pq fez oq fez ou mudar o que foi solicitado. E, então, passa pra pessoa revisora, de novo, olhar a situação. Tudo estando do jeito pedido ou a argumentação for convincente/adequada, você vai na opção de revisar de novo e seleciona a opção de aprovar. *(também pode ficar circulando entre desenvolvimento 🔄  revisão por um tempo se a coisa for mais cabeluda)*

Eu já podia encaminhar seus pedidos, mas vou esperar você vir atualizar aqui primeiro, pela prática 😉 

> Eu cheguei até fazer os testes de coleta com sucesso com base no [ba_candeias.py](https://github.com/okfn-brasil/querido-diario/blob/be5a58e2e4ea3c5e9faa97bd09cd002d6dd2ce96/data_collection/gazette/spiders/ba/ba_candeias.py)! Só pra registro mesmo!

Sobre isso, tava fazendo umas verificações ontem e notei que esse município é um homônimo! O raspador se chama Candeias **da Bahia**, mas a URL é **de Minas Gerais**. (*é sempre chato e detalhista esse tipo de situação* 😢 *)*

Ficou show o cuidado de validar um por um! Olhei seus logs e csvs. Eles parecem bons! 

Só teve um caso que precisa mudar: Itaporanga-SP. Ao ordenar o .csv da coleta completa, aparece que a primeira data é em 2009, mas a segunda data é 2011. Isso é bastante estranho. Busquei o documento no site e parece ter sido cadastrado errado pela prefeitura, pq as datas no documento são outras. Então, pra esse raspador, a data inicial correta é 2011-06-07. 

![image](https://github.com/user-attachments/assets/ad6ad360-d61f-484b-b00d-96bde5eacadc)
 
Você pode incluir essa solicitação de modificação na sua revisão, por favor? O item 8 desta [documentação do GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review) mostra como faz.

2024-10-04 17:53 UTC, jreagle commented
> A opção de aprovar só é selecionada quando a PR estiver pronta mesmo. No caso, você está solicitando que se faça remoções, então tinha que escolher "request changes". Isso vai bloquear a PR de seguir em frente enquanto as mudanças pedidas não forem endereçadas.

Nossa comi bola! Lendo agora faz total sentido isso!

> Aí a tarefa volta pra pessoa desenvolvedora, pra justificar pq fez oq fez ou mudar o que foi solicitado. E, então, passa pra pessoa revisora, de novo, olhar a situação. Tudo estando do jeito pedido ou a argumentação for convincente/adequada, você vai na opção de revisar de novo e seleciona a opção de aprovar. _(também pode ficar circulando entre desenvolvimento 🔄 revisão por um tempo se a coisa for mais cabeluda)_

Entendido, refazendo agora  e favoritando p/ posteridade!

> Eu já podia encaminhar seus pedidos, mas vou esperar você vir atualizar aqui primeiro, pela prática 😉

Altamente pedagógica! Como diria o Rolando Lero: "Capitei! Capitei, vossa mensagem"!

> Você pode incluir essa solicitação de modificação na sua revisão, por favor? O item 8 desta [documentação do GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review) mostra como faz.

Claro! Fazendo isso agora! Obrigado pelo baita aprendizado!

2024-10-04 17:56 UTC, jreagle requested changes
Refazendo a revisão de acordo com o "rito certo"!

2024-10-04 17:56 UTC, jreagle commented on data_collection/gazette/spiders/sp/sp_itaporanga.py
> +    start_date = date(2009, 4, 16)
```suggestion
    start_date = date(2011, 6, 7)
```
De acordo com a [revisão](https://github.com/okfn-brasil/querido-diario/pull/1281#issuecomment-2392431554) da revisão: 

> Só teve um caso que precisa mudar: Itaporanga-SP. Ao ordenar o .csv da coleta completa, aparece que a primeira data é em 2009, mas a segunda data é 2011. Isso é bastante estranho. Busquei o documento no site e parece ter sido cadastrado errado pela prefeitura, pq as datas no documento são outras. Então, pra esse raspador, a data inicial correta é 2011-06-07.

2024-10-04 21:24 UTC, trevineju commented
Obrigada! E acolhi suas solicitações, @jreagle! Pode dar uma olhada de novo? 😃  

> Claro! Fazendo isso agora! Obrigado pelo baita aprendizado!

hehehe 😊 

a parte legal disso é que, como você adicionou uma modificação diretamente na PR, você vira um co-participante. Pode ver que um dos commits é uma parceria.

2024-10-04 22:13 UTC, jreagle commented
> Obrigada! E acolhi suas solicitações, @jreagle! Pode dar uma olhada de novo se está pronto para aprovação? 😃

Sim! Eu que agradeço a oportunidade! 🙏💜
 
> a parte legal disso é que, como você adicionou uma modificação diretamente na PR, você vira um co-participante. Pode ver que um dos commits é uma parceria.

![giphy480p](https://github.com/user-attachments/assets/b5dcd780-d41b-4cab-be83-606b52b791d2)

2024-10-04 22:21 UTC, jreagle approved these changes
- [x] Remoção de raspador já existente da pull: [mg_juatuba.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/mg/mg_juatuba.py)
- [x] Remoção de raspador já existente da pull:  [mg_carmo_do_rio_claro.py](https://github.com/okfn-brasil/querido-diario/blob/fd9597ec2187ef2d3442cce30f58607befcd5bb2/data_collection/gazette/spiders/mg/mg_carmo_do_rio_claro.py#L7)
- [x] Atualização da variável "start_date" no arquivo [sp_itaporanga](https://github.com/okfn-brasil/querido-diario/pull/1281/files#diff-4bf586dbea6c19f47f18ae30fb0dcb46cb5b9cbd19d4d9c723b52845de1b1aec)

Parabéns pelo trabalho com os raspadores e revisão da revisão! 👏👏👏

2024-10-04 22:28 UTC, trevineju commented
Parabéns pela primeira revisão! ❤️

> revisão da revisão! 👏👏👏

A meta é, aos poucos, eu nem precisar mais validar a revisão de vocês 🚀   

O JP está trabalhando em melhorar o fluxo de revisão de PRs, mas enquanto não temos isso... se você quiser outra tarefa pra fazer, como foi essa aqui, pode escolher em #1284 (só lembra de deixar comentado na PR que vai revisar).

2024-10-04 22:35 UTC, trevineju commented
Mesclo a PR no projeto devido aprovação de @jreagle

2024-10-04 22:35 UTC, merged