Al maragogi
okfn-brasil/querido-diario pull request #1290
Opened 2024-09-29 14:17 UTC by victorfernandesraton

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [x ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [ ] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [ ] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [ ] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [ ] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [ ] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [ ] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [ ] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [ ] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [ ] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [ ] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [ ] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [ ] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

#### Descrição

<Descreva o seu Pull Request informando a issue (caso exista) que está sendo solucionada ou uma descrição do código apresentado>

2024-09-29 14:18 UTC, victorfernandesraton commented
Criei esta PR com base no que foi feito em https://github.com/okfn-brasil/querido-diario/pull/1186
Porém esta está dezatualizada,e devido a mudança nos raspadores eu acredito que revisar do começo faça mais sentido

2024-10-02 20:01 UTC, trevineju commented
Valeu, @victorfernandesraton! Coloquei na fila de revisão.

2024-10-09 19:45 UTC, ogecece requested changes
@victorfernandesraton o raspador tá bem eficiente. Tá ótimo requisitar todas as páginas disponíveis no intervalo de datas.

Fiz alguns comentários de melhoria aqui, qualquer coisa grita aí

2024-10-09 19:45 UTC, ogecece commented on data_collection/gazette/spiders/al/al_maragogi.py
> +    start_urls = ["https://diario.maragogi.al.gov.br"]
Como `.start_urls` seria em tese usado pelo `.start_requests()` padrão do Scrapy para gerar requisições com as URLs declaradas no atributo (como um atalho para não precisar declarar `.start_requests()` sempre), fica estranho usar o atributo e o método ao mesmo tempo, pois geralmente quando se implementa um não se usa o outro.

```suggestion
    BASE_URL = "https://diario.maragogi.al.gov.br"
```

2024-10-09 19:45 UTC, ogecece commented on data_collection/gazette/spiders/al/al_maragogi.py
> +        )
Três sugestões aqui:
- Aproveitar uma funcionalidade da `FormRequest` quando usada com `method=GET` de colocar o `formdata` na querystring da URL
- `per-page` pode ser removido pois não influencia no resultado (e infelizmente não pode ser regulado para aumentar o número de resultado por página)
- Fazer um método para gerar os params já que em outro método também está sendo criado praticamente igual
```suggestion
    def start_requests(self):
        yield scrapy.FormRequest(
            url=f"{self.BASE_URL}/busca",
            method="GET",
            formdata=self._build_formdata(),
        )

    def _build_formdata(self, page=1):
        return {
            "BuscaSearch[data_inicio]": self.start_date.strftime("%Y-%m-%d"),
            "BuscaSearch[data_fim]": self.end_date.strftime("%Y-%m-%d"),
            "BuscaSearch[sort]": "data_new",
            "BuscaSearch[modulo]": "diario-oficial",
            "page": str(page),
        }

```

2024-10-09 19:45 UTC, ogecece commented on data_collection/gazette/spiders/al/al_maragogi.py
> +            edition_number = self.__get_edition_number(title_parts, extra_edition)
Aqui daria pra simplificar o parsing de número de edição e ignorar a estrutura da string na edição extra (ficando um pouco mais resistente a possíveis variações)
```suggestion
            title_element = publication.css("h4 a::text")
            extra_edition = "extra" in title_element.get().lower()
            edition_number = title_element.re_first(r"nº (\d+)/", re.IGNORECASE)
```

2024-10-09 19:45 UTC, ogecece commented on data_collection/gazette/spiders/al/al_maragogi.py
> +            item_date = datetime.strptime(date_str, "%d de %B de %Y").date()
Como a gente já usa a `dateparser` no projeto, seria bem melhor usá-la do que reimplementar a funcionalidade
```suggestion
            date_raw = publication.css("div div div::text").getall()[1].strip()
            item_date = dateparser.parse(date_raw, languages=["pt"]).date()
```

2024-10-09 19:45 UTC, ogecece commented on data_collection/gazette/spiders/al/al_maragogi.py
> +                )
Aqui eu acho que fica mais limpo usar um `cb_kwargs` do que pegar a `page` da URL (se fossem mais parâmetros, pegar da URL poderia ser melhor). Com a sugestão que fiz acima de criar um método auxiliar `._build_formdata()` o código aqui poderia dar uma reduzida.

E também sugiro usar cláusula de guarda (imagino que seja essa a tradução pra `guard clause`) pra reduzir o espaçamento horizontal quando possível.

```python
def parse(self, response, current_page=1):

...

        if current_page > 1:
            return

        last_page = self.__get_total_pages(response)
        for page in range(2, last_page + 1):
            yield scrapy.FormRequest(
                url=f"{self.BASE_URL}/busca",
                method="GET",
                formdata=self._build_formdata(page),
                cb_kwargs={"current_page": page},
            )

```

2024-10-09 19:45 UTC, ogecece commented on data_collection/gazette/spiders/al/al_maragogi.py
Eu acho melhor deixar os métodos auxiliares no final da classe e o fluxo principal (`.start_requests()` e `.parse()`) ficar no começo, já que é a prioridade da leitura

2024-10-16 03:18 UTC, victorfernandesraton commented
Segue em anexos extração completa com csv e logs
[output-all.log](https://github.com/user-attachments/files/17388726/output-all.log)
[output-all.csv](https://github.com/user-attachments/files/17388727/output-all.csv)

2024-10-16 03:36 UTC, victorfernandesraton commented
Testes de busca entre 04-06-2024 e 02-07-2024
[output-06-07.log](https://github.com/user-attachments/files/17388813/output-06-07.log)
[output-06-07.csv](https://github.com/user-attachments/files/17388814/output-06-07.csv)

2024-10-16 03:47 UTC, victorfernandesraton commented on data_collection/gazette/spiders/al/al_maragogi.py
> +                )
@ogecece acho que o commit https://github.com/okfn-brasil/querido-diario/pull/1290/commits/a59d60fd990ec4548dffd49e3bd34c750bf95275 resolve isso

2024-10-16 17:40 UTC, ogecece approved these changes
Tá shou @victorfernandesraton !

2024-10-16 17:40 UTC, ogecece commented on data_collection/gazette/spiders/al/al_maragogi.py
> +                formdata={"page": str(page), **self.__create_params()},
:100:

2024-10-16 17:43 UTC, ogecece commented
@victorfernandesraton vou fazer squash pra ficar somente um commit do @gabrielqr e um seu, beleza? Como é apenas um raspador, 12 commits onde a maioria é de correções ficaria excessivo. Normalmente apenas 1 já seria suficiente

2024-10-16 17:46 UTC, merged