sistema replicavel administracaopublica #1247
okfn-brasil/querido-diario pull request #1297
Opened 2024-10-04 21:25 UTC by almeidadm

**AO ABRIR** uma *Pull Request* de um novo raspador (*spider*), marque com um `X` cada um dos items da checklist abaixo. Caso algum item não seja marcado, JUSTIFIQUE o motivo.

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [ ] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [X] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [X] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [X] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [X] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [X] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [X] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [X] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [X] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [X] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.

#### Verificações
- [X] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-coletados) não encontrando problemas.
- [X] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.
- [X] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#arquivos-auxiliares) não encontrando problemas.

[ma_nova_iorque_arbitrario.csv](https://github.com/user-attachments/files/17263858/ma_nova_iorque_arbitrario.csv)
[ma_nova_iorque_arbitrario.log](https://github.com/user-attachments/files/17263859/ma_nova_iorque_arbitrario.log)
[ma_nova_iorque_completo.csv](https://github.com/user-attachments/files/17263860/ma_nova_iorque_completo.csv)
[ma_nova_iorque_completo.log](https://github.com/user-attachments/files/17263861/ma_nova_iorque_completo.log)
[ma_nova_iorque_mais_recente.log](https://github.com/user-attachments/files/17263862/ma_nova_iorque_mais_recente.log)

#### Descrição

O sistema replicável foi feita através da consulta ao domínio _administracaopublica.com.br_. Neste domínio podemos reutilizar os tokens identificadores do domínio originalmente apresentado na Issue #1247 _transparenciadministrativa.com.br_.

Neste novo domínio a consulta ao endereço do arquivo pdf pode ser feita de maneira direta enquanto percorre o site, além de que as alterações de data podem ser feitas diretamente na url consultada.

O raspador consulta os boletins em um intervalo de 20 em 20 dias, correspondendo ao número máximo de boletins a serem mostrados sem navegação em paginação de resultados. Com isso podemos evitar a interação com elementos de renderização dinâmica no site.

2024-10-04 21:34 UTC, trevineju commented
boa, @almeidadm! Pode deixar um comentário na issue, por favor? Tenho tentado manter o [quadro de tarefas atualizado](https://github.com/orgs/okfn-brasil/projects/12/views/34) com as pessoas atuando nas issues, e se vc não comentar lá, o GitHub não permite que eu cadastre que você fez. 😓 

Colocando tb na fila de revisão ;)

2024-12-05 19:57 UTC, firefueled requested changes
Boa @almeidadm!

A task pede para a inclusão de Turilândia ttambém.
Pode incluir este município?

Além disso o código está top! Falta uma coisinha só

2024-12-05 19:57 UTC, firefueled commented on data_collection/gazette/spiders/base/administracaopublica.py
> +        gazettes = response.css(".diario_item_diario__g9Qfw")
Este seletor com hash no sufixo pode causar problemas caso o site seja atualizado.
Este hash é adicionado por algum framework frontend que gera html, e dependendo da sua configuração, pode ser modificado sem aviso prévio e frequentemente, resultando em falha do raspador.

Felizmente, podemos remover o sufixo do seletor no Scrapy e usar a sintaxe que faz a busca pelo começo do nome da classe.
Vejo que usou dessa sintaxe na linha 38. Pode usar ela aqui também?

2024-12-09 18:00 UTC, firefueled commented
Valeu @almeidadm !
Agora só ficaram faltando os arquivos csv e log referentes a peritoro e turilândia.
Desculpe por nao alertar para isso no meu último comentário :)

2025-01-21 23:54 UTC, trevineju commented
@almeidadm, obrigada pela PR! Agilizei a revisão e já acomodei as modificações para desempacar logo o problema em produção que ela resolve. 

As modificações feitas foram: 
1. Remoção de tipagens que não faz parte do padrão de projeto do repositório. 

2. Ajuste na criação da lista de datas
![image](https://github.com/user-attachments/assets/7cc7bfe6-5a7d-4081-8b04-440b9ef04528)

Aqui por dois motivos: rrule cria uma recorrência de datetime e self.end_date é date, mais pra frente no código ele reclamava entre não ser possível comparar date e datetime. O segundo motivo é que só adicionar end_date, sem verificar se já estava ou não, permitia o caso em que o end_date existia duas vezes na lista.

3. Ajuste no reconhecimento do padrão
![image](https://github.com/user-attachments/assets/c012d0d8-2075-4bd4-ae37-3b54b2e891b5)
Talvez o site tenha sido atualizado entre você fazer a PR e esta revisão, mas adicionaram uma coluna nova na página. Aí impactou o preenchimento dos metadados. 

4. Muitos redirecionamentos
Os logs (abaixo) estão com muitos casos de redirect, mas era pq faltou o www no link 
![image](https://github.com/user-attachments/assets/4b057b7a-6df1-450f-a0b4-cac55df399e1)

5. Troca do intervalo da recorrência
![image](https://github.com/user-attachments/assets/bfd8764b-fb2b-4a55-90be-ced2a0e0d189)

> O raspador consulta os boletins em um intervalo de 20 em 20 dias, correspondendo ao número máximo de boletins a serem mostrados sem navegação em paginação de resultados. Com isso podemos evitar a interação com elementos de renderização dinâmica no site.

O problema aqui são as edições "outras". Como você usou o limite da capacidade da página, não deixou espaço para casos de edições extras e de terceiros. Ou seja, em 20 dias, não necessariamente tem 20 edições; pode ter, seila, 28, por incluir algumas extras e de terceiros. O raspador perde essas edições, visto que não está paginando. 

No print, coloquei 10 como exemplo, pensando que pode ser uma boa margem, mas estou rodando as coletas completas dos 3 raspadores dessa PR para intervalos de 20, 10, 7 e 5 dias. Assim que acabar verifico qual ficou melhor

2025-01-22 00:47 UTC, almeidadm commented
> @almeidadm, obrigada pela PR! Agilizei a revisão e já acomodei as modificações para desempacar logo o problema em produção que ela resolve.
> 
> As modificações feitas foram:
> 
>     1. Remoção de tipagens que não faz parte do padrão de projeto do repositório.
> 
>     2. Ajuste na criação da lista de datas
>        ![image](https://private-user-images.githubusercontent.com/44185775/405407823-7cc7bfe6-5a7d-4081-8b04-440b9ef04528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1MDY5ODUsIm5iZiI6MTczNzUwNjY4NSwicGF0aCI6Ii80NDE4NTc3NS80MDU0MDc4MjMtN2NjN2JmZTYtNWE3ZC00MDgxLThiMDQtNDQwYjllZjA0NTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDAwNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNGQ3ZjNmMjI1MmM3MjJmM2FhOTFmNDk0Yzc4Y2MzODhlYmE4MzY0Y2M4OThiNmEzM2U5MGNhZTdhODM0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CeOgR-zf8P-HwCU-y2UzX6w-tp27jRRBo5rWp1E2TBc)
> 
> 
> Aqui por dois motivos: rrule cria uma recorrência de datetime e self.end_date é date, mais pra frente no código ele reclamava entre não ser possível comparar date e datetime. O segundo motivo é que só adicionar end_date, sem verificar se já estava ou não, permitia o caso em que o end_date existia duas vezes na lista.
> 
>     3. Ajuste no reconhecimento do padrão
>        ![image](https://private-user-images.githubusercontent.com/44185775/405408569-c012d0d8-2075-4bd4-ae37-3b54b2e891b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1MDY5ODUsIm5iZiI6MTczNzUwNjY4NSwicGF0aCI6Ii80NDE4NTc3NS80MDU0MDg1NjktYzAxMmQwZDgtMjA3NS00YmQ0LWFlMzctM2I1NGIyZTg5MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDAwNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNDU1NGM1MGRlZDNjMzcyZmQ3NmE5ZmFjNDM4M2YyZGM2ZTY2ZjM3MGM1OWNiNGY1MDgxNDkyMTM2MDk3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4Uk51ExkWtuRW7Xc6LLdyz1kA1VD0-sxorY44mPaoPY)
>        Talvez o site tenha sido atualizado entre você fazer a PR e esta revisão, mas adicionaram uma coluna nova na página. Aí impactou o preenchimento dos metadados.
> 
>     4. Muitos redirecionamentos
>        Os logs (abaixo) estão com muitos casos de redirect, mas era pq faltou o www no link
>        ![image](https://private-user-images.githubusercontent.com/44185775/405409329-4b057b7a-6df1-450f-a0b4-cac55df399e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1MDY5ODUsIm5iZiI6MTczNzUwNjY4NSwicGF0aCI6Ii80NDE4NTc3NS80MDU0MDkzMjktNGIwNTdiN2EtNmRmMS00NTBmLWEwYjQtY2FjNTVkZjM5OWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDAwNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYTE2YWZlZGEyYjlmMTcxN2M4YzA3Y2E5NTYxNzRhYWRhOTc0MDEwYWY0ZTI3ZDdiZGE3M2QwNzcxNTg5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Oj9Gy_CBq41l-aLeDp-YXqELxXulG003eSSElB71rxc)
> 
>     5. Troca do intervalo da recorrência
>        ![image](https://private-user-images.githubusercontent.com/44185775/405409484-bfd8764b-fb2b-4a55-90be-ced2a0e0d189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1MDY5ODUsIm5iZiI6MTczNzUwNjY4NSwicGF0aCI6Ii80NDE4NTc3NS80MDU0MDk0ODQtYmZkODc2NGItZmIyYi00YTU1LTkwYmUtY2VkMmEwZTBkMTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIyVDAwNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMmM5M2I1MzFiNWNkYTM4OGU1MTA5NzA4Y2M2NDY4OTRiZmNkNTQ1MmYzNzAzMmE0YzFmNDUyNGM1YzFmZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AteeuorvZi0CqJQ9E_YXThiSJFiRJ8UaKRSzhIL3kSE)
> 
> 
> > O raspador consulta os boletins em um intervalo de 20 em 20 dias, correspondendo ao número máximo de boletins a serem mostrados sem navegação em paginação de resultados. Com isso podemos evitar a interação com elementos de renderização dinâmica no site.
> 
> O problema aqui são as edições "outras". Como você usou o limite da capacidade da página, não deixou espaço para casos de edições extras e de terceiros. Ou seja, em 20 dias, não necessariamente tem 20 edições; pode ter, seila, 28, por incluir algumas extras e de terceiros. O raspador perde essas edições, visto que não está paginando.
> 
> No print, coloquei 10 como exemplo, pensando que pode ser uma boa margem, mas estou rodando as coletas completas dos 3 raspadores dessa PR para intervalos de 20, 10, 7 e 5 dias. Assim que acabar verifico qual ficou melhor.
> 
> Até lá, seguem os logs da coleta do ultimo dia e de período, funcionando bem: [ma_peritoro_periodo_1mes.log](https://github.com/user-attachments/files/18497814/ma_peritoro_periodo_1mes.log) | [ma_peritoro_periodo_1mes.csv](https://github.com/user-attachments/files/18497816/ma_peritoro_periodo_1mes.csv) [ma_turilandia_periodo_1mes.log](https://github.com/user-attachments/files/18497817/ma_turilandia_periodo_1mes.log) | [ma_turilandia_periodo_1mes.csv](https://github.com/user-attachments/files/18497818/ma_turilandia_periodo_1mes.csv) [ma_nova_iorque_periodo_1mes.log](https://github.com/user-attachments/files/18497819/ma_nova_iorque_periodo_1mes.log) | [ma_nova_iorque_periodo_1mes.csv](https://github.com/user-attachments/files/18497820/ma_nova_iorque_periodo_1mes.csv) [ma_peritoro_ultima.log](https://github.com/user-attachments/files/18497821/ma_peritoro_ultima.log) | [ma_peritoro_ultima.csv](https://github.com/user-attachments/files/18497822/ma_peritoro_ultima.csv) [ma_turilandia_ultima.log](https://github.com/user-attachments/files/18497823/ma_turilandia_ultima.log) | [ma_turilandia_ultima.csv](https://github.com/user-attachments/files/18497824/ma_turilandia_ultima.csv) [ma_nova_iorque_ultima.log](https://github.com/user-attachments/files/18497825/ma_nova_iorque_ultima.log) | [ma_nova_iorque_ultima.csv](https://github.com/user-attachments/files/18497826/ma_nova_iorque_ultima.csv)

Boa, @trevineju!
Tive alguns problemas nessa branch e acabei não conseguindo resolver.
Fico feliz que consegui contribuir pra essa solução!

Também agradeço os comentários sobre as alterações aplicadas! Assim consigo me atentar a essas questões, ou outras similares, em PRs futuros!

2025-01-22 01:13 UTC, trevineju commented
> Boa, @trevineju! Tive alguns problemas nessa branch e acabei não conseguindo resolver. Fico feliz que consegui contribuir pra essa solução!
> 
> Também agradeço os comentários sobre as alterações aplicadas! Assim consigo me atentar a essas questões, ou outras similares, em PRs futuros!

<img src="https://media1.giphy.com/media/tsX3YMWYzDPjAARfeg/giphy.gif"/>

2025-01-22 01:17 UTC, merged