Atualiza spider de rj-campos para usar start_date
okfn-brasil/querido-diario pull request #1323
Opened 2024-11-13 22:34 UTC by slfabio

**AO ABRIR** uma *Pull Request* de um novo raspador (*spider*), marque com um `X` cada um dos items da checklist abaixo. Caso algum item não seja marcado, JUSTIFIQUE o motivo.

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [x] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [ ] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [x] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [ ] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.

Foi adotado o start_date 01/11/2013, conforme decisão em https://github.com/okfn-brasil/querido-diario/issues/637#issuecomment-2447946814, pois de out/2012 a out/2013 os diários estão armazenados compactados em extensão .rar

- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.
[completa.csv](https://github.com/user-attachments/files/17786939/completa.csv)
[completa.log](https://github.com/user-attachments/files/17786940/completa.log)
[intervalo.csv](https://github.com/user-attachments/files/17786941/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/17786942/intervalo.log)
[ultima.csv](https://github.com/user-attachments/files/17786943/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/17786944/ultima.log)

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-data-collection-data) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#tabela-da-coleta-arquivo-csv) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#log-arquivo-log) não encontrando problemas.

#### Descrição

resolve #637 
Adiciona atributo start_date e edition_number ao spider de Campos RJ.

Alguns diários oficiais possuem erros de digitação, no código anterior já havia um replace para tratar alguns casos, corrigindo algumas ocorrências para as grafias incorretas: "Agosoto" e "Dezembrbo".
No entanto, ao rodar os testes foi identificado mais um erro de digitação na edição "Suplemento do Diário Oficial Eletrônico de 04 de Abril0 de 2024 - Edição - 1547".

Ao invés de adicionar mais um replace e visando uma solução que funcione para futuros erros de digitação, utilizei a biblioteca fuzzywuzzy, que usa o algoritmo de distância Levenshtein para medir a semelhança entre duas strings e, a partir da lista de meses, selecionar o mês com a grafia correta antes de fazer o dateparser.

Para usar o fuzzywuzzy, é necessário instalar 2 bibliotecas ao projeto:
pip install fuzzywuzzy
pip install python-Levenshtein

Caso a solução seja aceita, poderíamos mover o método extract_date para o utils do projeto para poder ser usado por outros spiders de diários que possuem a data do diário com o mês passado por extenso.

2024-11-18 21:15 UTC, slfabio commented
Oi @trevineju, estou atualizando o código do PR #563 para incluir os atributos obrigatórios do spider e identifiquei a mesma situação de meses com grafia incorreta gerando erro no dateparser.

Antes de enviar o código para Barra Mansa, queria ver o que você acha dessa solução para correção de erros de digitação no mês para reaproveitar o método extract_date no utils do projeto.

2025-02-20 13:03 UTC, firefueled commented
Como mencionou antes, podemos usar a mesma lógica de detecção de erros lá da #1333.
Junto com a mudança similar no nome do arquivo e classe.

2025-02-20 13:04 UTC, firefueled requested changes
Como mencionou antes, podemos usar a mesma lógica de detecção de erros lá da #1333.
Junto com a mudança similar no nome do arquivo e classe.

2025-02-20 14:12 UTC, slfabio commented
Bom dia @firefueled, 
vou aguardar a integração do PR #1333 para usar atualizar esse código.

Só pra avisar que enviei semana passada subimos um código no PR 1375 correção de um bg em produção que afeta 6 municípios.

2025-02-25 14:29 UTC, firefueled commented
@slfabio Boa.
Revisarei este em seguida

2025-04-20 15:41 UTC, trevineju approved these changes
Revisei a lógica e tá show. Só alguns casos que a data não está pegando direito, mas aí é com a utils #1389 que precisa ser incrementada. 

Tô aprovando a PR, que fica no aguardo da outra PR ser integrada.

2025-04-28 03:08 UTC, merged