Cria spider para Duque de Caxias RJ no padrão atual do projeto
okfn-brasil/querido-diario pull request #1333
Opened 2024-12-15 12:51 UTC by slfabio

**AO ABRIR** uma *Pull Request* de um novo raspador (*spider*), marque com um `X` cada um dos items da checklist abaixo. Caso algum item não seja marcado, JUSTIFIQUE o motivo.

#### Layout do site publicador de diários oficiais
Marque apenas um dos itens a seguir:
- [x] O *layout* não se parece com nenhum caso [da lista de *layouts* padrão](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/lista-sistemas-replicaveis.html)
- [ ] É um *layout* padrão e esta PR adiciona a spider base do padrão ao projeto junto com alguns municípios que fazem parte do padrão.
- [ ] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.

#### Código da(s) spider(s)
- [x] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [x] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gazette).
- [x] O atributo de classe [start_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.start_date) foi preenchido com a data da edição de diário oficial mais antiga disponível no site.
- [x] Explicitar o atributo de classe [end_date](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider.end_date) não se fez necessário.
- [x] Não utilizo `custom_settings` em meu raspador.

#### Testes
- [x] Uma coleta-teste **da última edição** foi feita. O arquivo de `.log` deste teste está anexado na PR.
- [x] Uma coleta-teste **por intervalo arbitrário** foi feita. Os arquivos de `.log`e `.csv` deste teste estão anexados na PR.
- [x] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.
[completa.csv](https://github.com/user-attachments/files/18140374/completa.csv)
[completa.log](https://github.com/user-attachments/files/18140375/completa.log)
[intervalo.csv](https://github.com/user-attachments/files/18140376/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/18140377/intervalo.log)
[ultima.csv](https://github.com/user-attachments/files/18140378/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/18140379/ultima.log)

#### Verificações
- [x] Eu experimentei abrir alguns arquivos de diários oficiais coletados pelo meu raspador e verifiquei eles [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#diarios-oficiais-data-collection-data) não encontrando problemas.
- [x] Eu verifiquei os arquivos `.csv` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#tabela-da-coleta-arquivo-csv) não encontrando problemas.
- [x] Eu verifiquei os arquivos de `.log` gerados pela minha coleta [conforme a documentação](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#log-arquivo-log) não encontrando problemas.

#### Descrição

Resolve #616 

Atualiza o código do PR #705 para o padrão atual do projeto, coletando todos os atributos do gazette.

Obs. Foi utilizada a data inicial de 02/01/2017, pois as versões anteriores não disponibilizam a data da edição. Os diários anteriores a 2017 exibem apenas a data de modificação do arquivo, que não tem relação com a data de publicação do diário.

Obs2. Revisar esse PR anrtes do #1323, pois se for integrada a função extract_date no utils, eu modificarei o código do spider de Campos-RJ para usar o método do utils.

Adiciona a função extract_date no utils do projeto para fazer o parse das datas escritas por extenso, corrigindo eventuais erros de digitação no mês.

O código utiliza a biblioteca fuzzywuzzy, que usa o algoritmo de distância Levenshtein para medir a semelhança entre duas strings e, a partir da lista de meses, selecionar o mês com a grafia correta antes de fazer o dateparser.

Para usar o fuzzywuzzy, é necessário instalar 2 bibliotecas ao projeto: **fuzzywuzzy** e **python-Levenshtein**

2025-02-18 18:37 UTC, firefueled requested changes
Valeu @slfabio .
Tem algumas coisinhas para fazermos antes de aceitar.
Favor ver comentários.

Outra coisa, em relação ao que disse aqui:
> Foi utilizada a data inicial de 02/01/2017, pois as versões anteriores não disponibilizam a data da edição. Os diários anteriores a 2017 exibem apenas a data de modificação do arquivo, que não tem relação com a data de publicação do diário.

Apesar da data da edição de diários antigos não estar explicita na página que contém os links para baixar, é possível extraí-la atraéz da url final de download dos diários.
Por exemplo: `https://duquedecaxias.rj.gov.br/portal/boletim-oficial/2014/07-Julho/6148-15.pdf`
O ano, mês, e dia estão aí. O dia é o número após a edição.

Isso não implica na não aceitação desta PR, mas significa que teremos que escrever outro raspador para pegar aqueles restantes.

2025-02-18 18:48 UTC, firefueled commented
[Tarefa criada](https://github.com/okfn-brasil/querido-diario/issues/1380) para os diários antigos, caso aceitemos esta PR sem fazer isso.

2025-02-18 19:01 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_duque_caxias.py
> +            is_extra_edition = bool(
Exatamente. São a continuação de uma mesma edição.

2025-02-18 19:22 UTC, slfabio commented on data_collection/gazette/utils.py
> +    return parsed_datetime.date() if parsed_datetime else None
Esse é um problema recorrente em municípios que utilizam data por extenso (Ex: Duque de Caxias/RJ, Barra Mansa/RJ, Campos/RJ)

Até deixei esse comentário na issue de Campos/RJ (https://github.com/okfn-brasil/querido-diario/pull/1323#issuecomment-2484146982) para saber o que vocês acham da solução, a ideia seria mover esse trecho do código para o utils do projeto e poder reaproveitar para outros municípios.

Sobre a quantidade de ocorrências eu precisaria eu posso testar novamente nesses 3 municípios para saber, acho que não chega a 10 edições para cada município, mas pra mim o principal é que mesmo que seja pontual, o problema ocorre em diversos municípios e a há uma solução simple de contorno.

2025-02-18 19:46 UTC, firefueled commented on data_collection/gazette/utils.py
> +    return parsed_datetime.date() if parsed_datetime else None
Entendido.
Concordo que vale a pena implementar essa estratégia.

2025-02-18 22:25 UTC, slfabio commented on data_collection/gazette/utils.py
> +    return parsed_datetime.date() if parsed_datetime else None
Alterado nome da função alterado.

2025-02-18 22:25 UTC, slfabio commented on data_collection/gazette/utils.py
> +from fuzzywuzzy import process
Alterações realizadas nos arquivos de requirements.

2025-02-18 22:26 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_duque_caxias.py
> +    name = "rj_duque_caxias"
Corrigido.

2025-02-19 13:48 UTC, firefueled commented on data_collection/gazette/spiders/rj/rj_duque_caxias.py
Obrigado pelas mudanças! Faltou só modificar o nome do arquivo em si. Para `rj_duque_de_caxias.py`

2025-02-19 15:59 UTC, slfabio commented on data_collection/gazette/spiders/rj/rj_duque_caxias.py
Feito!

2025-02-19 16:42 UTC, firefueled commented
@trevineju pode juntar essa!

2025-04-18 18:32 UTC, trevineju commented
@slfabio @firefueled... peguei essa PR pra olhar há umas semanas e, como adiciona uma utils, puxei o commit do Fábio para #1389 e continuei lá. Revisar um utilitário -- que se espera servir pra muitos raspadores -- é uma tarefa grande por si só. Isso se misturar com a revisão de Duque de Caxias é ruim. 

Pelo mesmo motivo (o utilitário precisar ser usado em muitos casos), o escopo da PR cresceu muito: já migrei todos os raspadores que importam dateparser para passar a importar o utilitário. Inclusive adicionei testes unitários também. Inauguramos o uso de testes para o util de datas (#1388) e também pq muito em breve vamos migrar o modelo do banco de dados do QD (#1383) então ter robustez no tratamento de datas se tornou muito relevante, pros dados entrarem melhor em nosso banco. 

Vou deixar algumas devolutivas aqui, de aspectos que levei em consideração pra outra PR. Mas vou remover tudo de utils desta PR e manter apenas Duque de Caxias. Convido vocês a dar uma olhada na PR nova: #1389

2025-04-18 18:51 UTC, trevineju commented on data_collection/gazette/utils.py
> +    return parsed_datetime.date() if parsed_datetime else None
Tá ótima a lógica de se antever e já deixar solucionado um problema que pode seguir aparecendo. A utils pode seguir sendo aprimorada com o tempo, sempre que uma nova situação aparecer. 

Mas prefiro o nome anterior. Não acho que não precisa ficar evidente como a função resolve o problema. Inclusive, parte da ideia de se ter um utilitário pronto pra uso regular é "esconder" como aquilo foi resolvido, só importa que foi resolvido e tá ali pronto pra ser usado. Deixar documentado basta.

2025-04-18 18:56 UTC, trevineju commented on data_collection/gazette/utils.py
> +from fuzzywuzzy import process
Show aqui, mas troquei a lib para [thefuzz](https://github.com/seatgeek/thefuzz). O motivo foi que a própria [documentação da fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) informou da migração.

Parece ter os mesmos recursos, até mesmo com a mesma assinatura. Troquei o import e praticamente não precisei mudar as linhas de código.

2025-04-19 13:12 UTC, trevineju commented
Eu só troquei a chamada da utils e executei o raspador de novo. Mas não revisei a lógica dele visto que @firefueled já o fez. 
[rj_duque_de_caxias.log](https://github.com/user-attachments/files/19821288/rj_duque_de_caxias.log)
[rj_duque_de_caxias.csv](https://github.com/user-attachments/files/19821289/rj_duque_de_caxias.csv)

2025-04-19 13:12 UTC, trevineju approved these changes

2025-04-19 21:58 UTC, slfabio commented
Muito obrigado, @trevineju !

2025-04-22 17:55 UTC, firefueled commented on data_collection/gazette/utils.py
> +    return parsed_datetime.date() if parsed_datetime else None
@trevineju Concordo que não há necessidade de expor a implementação. Minha preocupação ao sugerir a mudança no nome foi de explicitar a função do método e sua assinatura.

`date_from_text_with_fuzzy_match` explica qual é a entrada, a saída, e o que o método faz para transformar um no outro. Assim, qualquer leitor saberá o que está sendo feito na chamada do método, incluindo o que está sendo passado e o que está sendo recebido.

Me preocupo que um nome muito genérico necessite análise mais profunda por um leitor  para entender o que está acontecendo na sua chamada.

2025-04-22 17:58 UTC, firefueled approved these changes

2025-04-28 03:13 UTC, merged