Add new spider for Macapa-AP
okfn-brasil/querido-diario pull request #217
Opened 2020-08-20 01:06 UTC by rennerocha

This PR solves https://github.com/okfn-brasil/querido-diario/issues/180.

Macapa page only provide gazettes from 2020.

2020-08-31 20:19 UTC, giuliocc commented
Looks fine :) What should we do about the image PDFs?

2020-09-15 19:41 UTC, jvanz requested changes

2020-09-15 19:41 UTC, jvanz commented on processing/data_collection/gazette/spiders/ap_macapa.py
> +import scrapy
```suggestion
from urllib.parse import urlencode
import datetime as dt

from dateparser import parse
import scrapy
```

2020-09-15 19:43 UTC, jvanz commented
> Looks fine :) What should we do about the image PDFs?

I believe we should merge the spider even if we cannot read the data. In the end of the day, we can attack this issue in the future.

2020-10-03 13:08 UTC, ejulio approved these changes

2020-10-03 13:08 UTC, ejulio commented on processing/data_collection/gazette/spiders/ap_macapa.py
> +        today = dt.date.today()
I guess you just need to adapt it for the incremental crawl before merging

2020-10-08 09:17 UTC, alexandrevicenzi requested changes

2020-10-08 09:17 UTC, alexandrevicenzi commented on processing/data_collection/gazette/spiders/ap_macapa.py
> +                r"[Dd][Ee] (\d{2} [Dd][Ee] [\w]+ [Dd][Ee] \d{4})"
@rennerocha what about looking for `fa-file-pdf-o` select and getting it's parent? this way you get the PDF url.

If you look for `panel-body` inside `panel` you can also get the URL if there's and `a` tag.

2021-08-11 17:06 UTC, anapaulagomes commented
Closing this one since we already have a spider for Macapá.

2021-08-11 17:06 UTC, closed without merging