adding jaboatao spider
okfn-brasil/querido-diario pull request #227
Opened 2020-08-28 02:28 UTC by andersonberg

This PR adds a spider for the Jaboatão dos Guararapes city in Pernambuco.
I had to add `application/octet-stream` as a valid file type because the magic is identifying all the pdf's this way.
I'm not sure if it's the best solution, so I'm open to suggestions.

2020-09-01 16:02 UTC, giuliocc commented
I think this is due to `libmagic`'s version on the docker image. In my machine I'm using version 5.39 and it detects these PDFs correctly.

I think `octet-stream` is not good to indicate the filetype as other types can be falsely defaulted to `octet-stream` too :/

_Sidenote: I tried using `magic.from_buffer` with the first 1024 and 2048 bytes and the error still occurred._

2020-09-01 20:01 UTC, andersonberg commented
Nice catch @giuliocc! I'll test with the version you mentioned. Thanks for the help

2020-09-16 00:40 UTC, jvanz requested changes

2020-09-16 00:40 UTC, jvanz commented on processing/data_collection/gazette/spiders/pe_jaboatao_dos_guararapes.py
> +
```suggestion
from datetime import datetime

from dateparser import parse
from scrapy import Request

```

See more in [PEP 8](https://www.python.org/dev/peps/pep-0008/#imports)

2020-09-16 00:42 UTC, jvanz commented
I have not run the spider yet (connection issue). I'll run it asap.

2020-09-16 14:07 UTC, jvanz commented
> I have not run the spider yet (connection issue). I'll run it asap.

Yeah, the spider s not working here.

```
2020-09-16 14:05:10 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-09-16 14:05:14 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://diariooficial.jaboatao.pe.gov.br/> (failed 1 times): An error occurred while connecting: 113: No route to host.
2020-09-16 14:05:18 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://diariooficial.jaboatao.pe.gov.br/> (failed 2 times): An error occurred while connecting: 113: No route to host.
2020-09-16 14:05:19 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET https://diariooficial.jaboatao.pe.gov.br/> (failed 3 times): An error occurred while connecting: 113: No route to host.
```

 @andersonberg, can you double check it?

2020-09-16 14:08 UTC, jvanz commented
> > I have not run the spider yet (connection issue). I'll run it asap.
> 
> Yeah, the spider s not working here.
> 
> ```
> 2020-09-16 14:05:10 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
> 2020-09-16 14:05:14 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://diariooficial.jaboatao.pe.gov.br/> (failed 1 times): An error occurred while connecting: 113: No route to host.
> 2020-09-16 14:05:18 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://diariooficial.jaboatao.pe.gov.br/> (failed 2 times): An error occurred while connecting: 113: No route to host.
> 2020-09-16 14:05:19 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET https://diariooficial.jaboatao.pe.gov.br/> (failed 3 times): An error occurred while connecting: 113: No route to host.
> ```
> 
> @andersonberg, can you double check it?

I'm trying to access the website. But no success. It seems offline to me...

2020-09-16 18:12 UTC, andersonberg commented
@jvanz it seems to be offline due to a hacker attack: https://g1.globo.com/pe/pernambuco/noticia/2020/09/14/site-da-prefeitura-de-jaboatao-dos-guararapes-e-hackeado-e-fica-fora-do-ar.ghtml

2020-09-16 19:07 UTC, jvanz commented
> @jvanz it seems to be offline due to a hacker attack: https://g1.globo.com/pe/pernambuco/noticia/2020/09/14/site-da-prefeitura-de-jaboatao-dos-guararapes-e-hackeado-e-fica-fora-do-ar.ghtml

=/
Your PR needs to wait until we are able to double check it... sorry.

2020-09-18 19:58 UTC, andersonberg commented
@jvanz the website is back up, you may be able to test the spider now

2020-09-29 01:18 UTC, jvanz commented
@andersonberg please, check this:

2020-09-29 01:15:55 [scrapy.pipelines.files] DEBUG: File (downloaded): Downloaded file from <GET https://diariooficial.jaboatao.pe.gov.br/26-de-setembro-de-2020-xxx-no-189-jaboatao-dos-guararapes/?pdf=22386> referred in <None>
2020-09-29 01:15:55 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2020, 9, 26, 0, 0),
 'file_urls': ['https://diariooficial.jaboatao.pe.gov.br/26-de-setembro-de-2020-xxx-no-189-jaboatao-dos-guararapes/?pdf=22386'],
 'files': [{'checksum': '0941699af6483902955d6923c5571e61',
            'path': 'full/714763826166e8c3eb75dea8acb2da65e0eedbdf',
            'url': 'https://diariooficial.jaboatao.pe.gov.br/26-de-setembro-de-2020-xxx-no-189-jaboatao-dos-guararapes/?pdf=22386'}],
 'is_extra_edition': False,
 'power': 'executive',
 'scraped_at': datetime.datetime(2020, 9, 29, 1, 15, 49, 262546),
 'territory_id': 2607901}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/mnt/code/data_collection/gazette/pipelines.py", line 39, in process_item
    "Unsupported file type: " + self.get_file_type(item["files"][0]["path"])
Exception: Unsupported file type: application/octet-stream

2020-10-03 13:06 UTC, ejulio approved these changes

2020-10-03 13:06 UTC, ejulio commented on processing/data_collection/gazette/spiders/pe_jaboatao_dos_guararapes.py
> +    TERRITORY_ID = 2607901
I think this should be a string

2020-10-03 13:06 UTC, ejulio commented on processing/data_collection/gazette/spiders/pe_jaboatao_dos_guararapes.py
> +            is_extra_edition=self.is_extra_edition(file_url),
I guess this can be simply `is_extra_edition= "edicao-extraordinaria" in fule_url`

2020-10-06 16:33 UTC, jvanz requested changes
Please, take a look in the error that I sent in the previous comments.

2020-10-06 16:33 UTC, jvanz commented on processing/data_collection/gazette/spiders/pe_jaboatao_dos_guararapes.py
> +    TERRITORY_ID = 2607901
Yeap. Please, use a string value.

2020-10-09 22:09 UTC, andersonberg commented
@jvanz those are the errors I mentioned in the PR description. I tried to upgrade the version of the libmagic in the docker image as @giuliocc pointed, but the apt-get says the version is the lastest one (5.30). So any help on that matter is more than welcome

2020-10-10 18:47 UTC, jvanz commented
> @jvanz those are the errors I mentioned in the PR description. I tried to upgrade the version of the libmagic in the docker image as @giuliocc pointed, but the apt-get says the version is the lastest one (5.30). So any help on that matter is more than welcome

Yeah, I discovered that after I've posted the comment. You just need to rebuild the container image with `make setup`.  xD

2020-10-10 19:08 UTC, jvanz commented
> `libmagic`

What is your distro? Are you using ubuntu or debian? If it's the same distro use inside the container, maybe we can use the repo with the latest library version. But we need to test that and check if this is possible.

2020-10-10 22:12 UTC, andersonberg commented
I use ubuntu and I have the libmagic version 5.37. `apt-get` says it's the latest version. I tested using this version, but the error still happening

2020-10-18 12:34 UTC, jvanz commented
@giuliocc can you check the package repository URL which give you access to libmagic `5.39` version?

2020-10-20 01:31 UTC, giuliocc commented
I tested it on Arch Linux. Should we consider building it from source?

2020-10-20 02:04 UTC, rennerocha commented
@andersonberg and @giuliocc 
Extract text content from files was removed from the project, so I believe that `libmagic` is not needed anymore.

2020-10-20 02:12 UTC, giuliocc commented
Oh, yeah, right :) Need some sleep hehehe

2020-10-26 15:50 UTC, andersonberg commented
@jvanz @giuliocc @rennerocha I merged with main branch and fixed date to meet the json schema requirements. Can you please test/review again? Thanks!

2020-10-29 11:51 UTC, jvanz approved these changes

2020-10-29 11:53 UTC, jvanz commented
The spider seems good to me. The only further comment I would suggest is try to use the `start_date` to avoid requesting page with dates not necessary.

2020-10-29 22:37 UTC, andersonberg commented
@jvanz I'm not sure, but I don't know how I could use the `start_date` login in this site. The site uses a simple pagination that goes back to 2015 with some gazettes in each page. Adding to that, in my opinion it would cost more run time to check each gazette date. Let me know what you have in mind and we can come with a better solution. Thanks!

2020-11-02 19:19 UTC, jvanz commented
I just had an idea. What do you think about a binary search in the pages? If we know the last page, we can get a page in the middle and check the dates. If the start_date is after those, we can ignore the oldest pages and so on... What do you think? How about you, @rennerocha @giuliocc ?

2020-11-04 03:13 UTC, giuliocc commented
I agree with what was said in the discussion group:

Going page by page might be better in this case.

As it is, this spider is already going page by page. So the easier thing to do would be filtering access to each gazette page based on the date shown in each gazette card and stopping pagination after reaching a certain date.

Is the effort for more efficiency worth it right now?

2021-08-09 09:00 UTC, anapaulagomes commented
The [website](https://diariooficial.jaboatao.pe.gov.br/) is still unavailable and it seems that Jaboatão now has a new DO's page: https://www.doinet.com.br/bdpv2/catalogo/default.aspx?publicacao=DOMJBO. Could you please confirm this @andersonberg?

2022-03-10 22:31 UTC, giuliocc commented
### Português

@anapaulagomes @andersonberg  o site voltou (:partying_face:) e DOinet é um serviço parecido com o QD, porém fechado. Assim, a única fonte de publicação atual para Jaboatão está de pé.

Aproveitei o PR que o @tcurvelo fez na Hacktoberfest  (#517 ) para dar uma atualizada nesse aqui e fiz pequenas modificações pra permitir filtro por datas.

Testei aqui e tá tudo funcionando de boinhas. Mesclando! Obrigado a todo mundo que colaborou! <3

### English

@anapaulagomes @andersonberg the website is back online (:partying_face:) and DOinet is a service which is similar to QD but closed. With that in mind, the only current publication source of Jaboatão is up.

@tcurvelo 's PR made in Hacktoberfest (#517) was used to make some updates in this one. And I added the date filter.

Everything is tested and working well. Merging it! Thanks to everyone who collaborated in this one! <3

2022-03-10 22:32 UTC, giuliocc commented
LGTM!

![_](https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif)

2022-03-10 22:32 UTC, merged