Add spider for Petrópolis/RJ
okfn-brasil/querido-diario pull request #282
Opened 2020-10-08 03:15 UTC by Jefersonalves

This PR solves #281

2020-10-08 09:09 UTC, alexandrevicenzi requested changes
I don't find this implementation clean or easy to understand, it seems that the code is trying to do too much, in too little code.

Petropolis uses a directory-based style to show the data that we want. I would expect the code to follow the same as:

- Follow Year directory
- Follow Month directory
- Parse Month page and yield all PDF links


The current code just looks for all links found in a broad way and use regex to figure out what function to call, this seems odd to me.

2020-10-08 09:09 UTC, alexandrevicenzi commented on processing/data_collection/gazette/spiders/rj_petropolis.py
> +        for entry in response.css("#col1 > div > table"):
You could get URLs using the selector `jd_download_url`.

2020-10-08 09:09 UTC, alexandrevicenzi commented on processing/data_collection/gazette/spiders/rj_petropolis.py
> +    set_to_discard = {
this seems like a hack because the implementation is not perfect or because the selectors are too broad.

2020-10-09 00:51 UTC, Jefersonalves commented
Hi @alexandrevicenzi. Thanks for the review. I made some changes to make the spider simpler, as you suggested. I think this PR is ready for a new review

2020-10-10 18:40 UTC, jvanz approved these changes

2020-10-13 02:51 UTC, giuliocc reviewed
The spider looks great! May I add just one little suggestion? Renaming the variables from `entry` to something like `year`, `month`, `gazette`, `document`, etc. Just to make it clearer when reading the code?

2020-10-17 19:03 UTC, Jefersonalves commented
> The spider looks great! May I add just one little suggestion? Renaming the variables from `entry` to something like `year`, `month`, `gazette`, `document`, etc. Just to make it clearer when reading the code?

@giuliocc Done!

2020-10-18 15:13 UTC, jvanz requested changes
The code looks good. But I would like to take the opportunity to start make the spider more efficient. We are in the process to adjust the spiders to avoid unnecessary requests.  To me, you should change the spider to consider the `start_date` when walking in the pages. This variable can be change by the users to define witch gazeetes they want. So, my suggestion is to check if you found a year which is not request, in other words, is before the `start_date`, ignore it. The same for the months and days. Therefore, your spider will be more efficient and faster.

2020-10-24 21:17 UTC, Jefersonalves commented
@jvanz the spider is now more efficient and considers the start date to reduce the number of requests. Travis is failing because of the formatting of the settings.py file in the main branch

2020-10-28 01:46 UTC, jvanz requested changes

2020-10-28 01:46 UTC, jvanz commented on processing/data_collection/gazette/spiders/rj_petropolis.py
> +    }
I think you should use the standard library for this:

```
➜  querido-diario git:(main) ✗ python3 test.py
janeiro
fevereiro
março
abril
maio
junho
julho
agosto
setembro
outubro
novembro
dezembro
➜  querido-diario git:(main) ✗ cat test.py 
import calendar

with calendar.different_locale("pt_BR.utf8") as different_locale:
    for number in range(1,13):
        print(calendar.month_name[number])
```

;-)

2022-08-30 15:14 UTC, rennerocha commented
Closed as stale.

2022-08-30 15:14 UTC, closed without merging