Added Spider for Vinhedo - SP
okfn-brasil/querido-diario pull request #283
Opened 2020-10-09 14:32 UTC by aassumpcao

2020-10-09 16:48 UTC, rennerocha requested changes
@aassumpcao thanks for you PR! I added a few comments and suggestions to improve the spider. Please let me know if you have some doubts about them.

2020-10-09 16:48 UTC, rennerocha commented on processing/data_collection/gazette/spiders/sp_vinhedo.py
> +    # define class variables
**suggestion**: This comment is not providing anything useful. It may be removed.

2020-10-09 16:48 UTC, rennerocha commented on processing/data_collection/gazette/spiders/sp_vinhedo.py
> +    allowed_domains = ['vinhedo.sp.gov.br']
**issue (blocking)**: All code must be formatted with black.

2020-10-09 16:48 UTC, rennerocha commented on processing/data_collection/gazette/spiders/sp_vinhedo.py
> +            if date >= self.start_date:
**suggestion**: There is no need to filter by date here. Get all gazettes available. Filtering should be done when defining the requests and by an existing pipeline that will drop items according to `start_date` argument.

2020-10-09 16:48 UTC, rennerocha commented on processing/data_collection/gazette/spiders/sp_vinhedo.py
> +    # parse gazette pages dynamically
**suggestion**: You can remove these comments. Code is self-explanatory.

2020-10-09 16:48 UTC, rennerocha commented on processing/data_collection/gazette/spiders/sp_vinhedo.py
> +    def parse_page(self, response):
**suggestion**: Processing the data by columns and then returning them using `zip` looks a bit unusual. As the gazettes are organized by lines, it is much easier (and more readable) to process each line like the following:

```
for gazette in response.css("table tbody tr"):
    # get the information about this gazette
    # then:
    yield Gazette(...)
```

2020-10-09 16:48 UTC, rennerocha commented on processing/data_collection/gazette/spiders/sp_vinhedo.py
> +        pages = response.xpath('//*[@class="page-numbers"]//@href').getall()
**suggestion**: Scrapy take care of not sending duplicated requests more than once, so you could simply send the page links available on the current page. When we are in a next page, new page links will appear and they will be correctly handled.

When searching for class attribute, give preference for CSS Selectors.

```
for page_url in response.css("a.page-numbers::attr(href)").getall():
    yield scrapy.Request(response.urljoin(page_url), self.parse_page)
```

2020-10-09 16:48 UTC, rennerocha commented on processing/data_collection/gazette/spiders/sp_vinhedo.py
> +    def parse_page(self, response):
**suggestion**: AS the URL in `start_urls` is already page 1, you could use the same `parse` method for all pages. No need to create a separated method. Just one is enough.

2020-11-03 20:55 UTC, giuliocc requested changes
@aassumpcao since the repository structure was recently changed, some conflicts appeared. Could you solve them or open a new PR incorporating the new changes (whatever works best for you).

Also, I think we could add `.DS_Store` files to `.gitignore`

2020-11-03 20:55 UTC, giuliocc commented on processing/data_collection/gazette/settings.py
> +QUERIDODIARIO_EXTRACT_TEXT_FROM_FILE = True
Since the text extraction was removed from the repository, this setting does not exist anymore.

2022-07-28 20:54 UTC, rennerocha commented
Finished at https://github.com/okfn-brasil/querido-diario/pull/599

2022-07-28 20:54 UTC, closed without merging