Add
okfn-brasil/querido-diario pull request #303
Opened 2020-10-12 02:23 UTC by gabubellon

Hello !!
Add Itu -SP spider.

A detail about this spider, Itu official [site](https://itu.sp.gov.br/imprensa-oficial/) use a javascript API from [DOSP](https://dosp.com.br) that return a JSON with journal details (ids and link), and use another API to parser a call to journal pdf.

Therefore I use a `chompjs` lib to parse javascript to a dict and parse data based on oficial [documentation](https://docs.scrapy.org/en/latest/topics/dynamic-content.html#parsing-javascript-code).

2020-10-12 14:42 UTC, adorilson commented
This PR is part of #298

2020-10-13 21:53 UTC, giuliocc requested changes
Very nice and clean implementation :) That was great!

Just tested and everything is working as expected.

Just made some minor corrections there and suggestions for improvement.

As both you and @adorilson pointed out, this spider is part of a system that can be replicated for multiple spiders. After this PR I think we could make another PR transforming most of this into a base spider and adding spiders for each remaining city. Would you want to do that?

2020-10-13 21:53 UTC, giuliocc commented on processing/data_collection/gazette/spiders/sp_itu.py
> +from gazette.spiders.base import BaseGazetteSpider
```suggestion
import base64
from datetime import datetime

import chompjs
import dateparser
from scrapy import Request, Spider

from gazette.items import Gazette
from gazette.spiders.base import BaseGazetteSpider
```

Just to follow PEP8's import rule.

2020-10-13 21:53 UTC, giuliocc commented on processing/requirements.txt
> +chompjs==1.0.16
Could you install `pip-tools` in your environment and then:
1. add `chompjs` to `requirements.in`
2. run `pip-compile requirements.in`
3. commit the modified `requirements.in` and `requirements.txt`

That way we can keep a more readable dependencies file (`requirements.in`) and a fixed dependency tree for an easy reproducible build (`requirements.txt`)

2020-10-13 21:53 UTC, giuliocc commented on processing/data_collection/gazette/spiders/sp_itu.py
> +            print(url)
I think the `print`s can be removed now :) They served their purpose

2020-10-13 21:53 UTC, giuliocc commented on processing/data_collection/gazette/spiders/sp_itu.py
> +            )
I think we can get the `edition_number` field from `"edicao_do"` too. Don't you think?

2020-10-13 22:51 UTC, gabubellon commented
CR and remove autogenerated gazette fields

2020-10-13 22:56 UTC, gabubellon commented
> Very nice and clean implementation :) That was great!
> 
> Just tested and everything is working as expected.
> 
> Just made some minor corrections there and suggestions for improvement.
> 
> As both you and @adorilson pointed out, this spider is part of a system that can be replicated for multiple spiders. After this PR I think we could make another PR transforming most of this into a base spider and adding spiders for each remaining city. Would you want to do that?

@giuliocc Thanks !
And Yes, I believe the next step is move to a base spider, but two things need check first:
* Get all the cities codes from DiOE (#298);
* Check if returned json are equals from all cities.
I like on work that !

2020-10-14 01:59 UTC, giuliocc approved these changes
LGTM! That was a great first contribution :)

If anyone else merges, remember to "Squash and Merge"

2020-10-16 02:08 UTC, merged

2020-10-16 03:09 UTC, giuliocc commented
Thank you so much for the contribution!!