feat: add Guarapuava/PR spider
okfn-brasil/querido-diario pull request #340
Opened 2020-11-01 20:22 UTC by Pr3d4dor

2020-11-02 19:51 UTC, jvanz requested changes

2020-11-02 19:51 UTC, jvanz commented on processing/data_collection/gazette/spiders/pr_guarapuava.py
> +from gazette.spiders.base import BaseGazetteSpider
```suggestion
import re
from datetime import date

from dateparser import parse
import scrapy

from gazette.items import Gazette
from gazette.spiders.base import BaseGazetteSpider
```

2020-11-02 19:51 UTC, jvanz commented on processing/data_collection/gazette/spiders/pr_guarapuava.py
> +    starting_year = 2001
Please, use the `start_date` from the `BaseGazetteSpider`

2020-11-07 19:27 UTC, Pr3d4dor commented
@jvanz The build is failing because of other files that I did not edit, what should I do now?

2020-11-08 20:31 UTC, giuliocc commented
> @jvanz The build is failing because of other files that I did not edit, what should I do now?

Don't worry about it :)

2020-11-20 00:41 UTC, jvanz requested changes
@Pr3d4dor I've fixed on conflict in the CITIES file. This merge the main branch in your branch.  However, we have changed the directory structure and your file is in the older path. Can you move it to the right path?

2020-11-20 03:16 UTC, Pr3d4dor commented
@jvanz done :)

2020-12-03 12:28 UTC, rennerocha requested changes
Thanks for your PR. I added a few suggestions to improve the code and a lot of nitpicks. Some of the nitpicks are more a personal preference than a real problem in the code. Please let me know if you have any questions about them.

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +    start_date = datetime(2002, 1, 20).date()
**suggestion**: You can create a `date` directly instead of converting a `datetime`to date:
`start_date = date(2002, 1, 20)`

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +                is_extra_edition=self.gazzete_is_extra_edition(link_str),
**suggestion**: As this is a one-line method, I think that just creating a new variable doing this check, inside `parse` method would be enough. Something like:
```
is_extra_edition = "extra" in link_str.get().lower()
yield Gazette(
    ...
)
```

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +        matches = re.findall(r"(\d+/\d+/\d+)", text)
**suggestion**: Scrapy (parsel) already has some methods to make the use o [regexes](https://parsel.readthedocs.io/en/latest/parsel.html#parsel.selector.Selector.re_first) easier. All this method can be replaced by:

`gazette_date = parse(gazette.css("a ::text").re_first(r"(\d+/\d+/\d+)), languages=["pt"]).date()`

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +        match = re.search(r"Boletim(\s+)Oficial(\s+)(\d+)", text)
**suggestion**: You can use the same logic as my last comment about how to extract dates using regexes in this method too.

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +                file_urls=[gazette.css("a::attr(href)").extract_first()],
**nitpick**: `get` instead of `extract_first`

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +            yield scrapy.Request(url=url, callback=self.parse)
**nitpick**: `self.parse` is already the default name of the `callback`. You don't need to provide it here.

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +        todays_date = date.today()
**nitpick**: Today is the end datewhere we try to get the gazettes: `end_date = date.today()`

2020-12-03 12:28 UTC, rennerocha commented on data_collection/gazette/spiders/pr_guarapuava.py
> +        for year in range(current_year, self.start_date.year - 1, -1):
**nitpick (very subjective)**: This looks nicer to me (very subjective. Ignore it if you don't agree).
```range(self.start_date.year, enddate.year + 1))```

2020-12-04 01:07 UTC, Pr3d4dor commented
@rennerocha Thanks for your review, I applied all the suggestions. The only one I could apply was the suggestion to use parsel `re_first` to extract the gazzette edition number.

2022-08-30 15:13 UTC, rennerocha commented
Closed as stale.

2022-08-30 15:13 UTC, closed without merging