Add São José do Rio Preto - SP Spider
okfn-brasil/querido-diario pull request #385
Opened 2020-11-23 10:08 UTC by fariaseduv

2020-12-03 12:29 UTC, rennerocha requested changes

2020-12-04 14:53 UTC, fariaseduv commented on data_collection/gazette/spiders/sp_sao_jose_do_rio_preto.py
> +from fake_useragent import UserAgent
Ok, done in the new commit.

2021-08-09 14:15 UTC, anapaulagomes commented
Thanks for your contribution, @farias-eduv! Could you please update `CITIES.md` for São José do Rio Preto - SP and also this branch with the latest changes in the `main` branch? I'd be happy to review right after this is done.

2022-08-30 15:14 UTC, rennerocha commented
Closed as stale.

2022-08-30 15:14 UTC, closed without merging