Added Lajeado - RS crawler
okfn-brasil/querido-diario pull request #397
Opened 2020-12-01 04:03 UTC by meyer1994

2020-12-03 12:08 UTC, rennerocha requested changes
Thanks for your PR. I added a few suggestions to make the code cleaner and following the project patterns and to improve the amount of data received. Please let me know if you have any questions about them.

2020-12-03 12:08 UTC, rennerocha commented on data_collection/gazette/spiders/rs_lajeado.py
> +            kwargs = {"filedate": self.extract_date(filename)}
**suggestion**: `gazette_date` looks a better name for this field.

2020-12-03 12:08 UTC, rennerocha commented on data_collection/gazette/spiders/rs_lajeado.py
> +            filename = item.css("::text").get()
**issue**: We are able to get `edition_number` from this text in all links. For example: `22/11/17_edição_0396 ` we should return `0396` as `edition_number`. This is an important information to be collected.

2020-12-03 12:08 UTC, rennerocha commented on data_collection/gazette/spiders/rs_lajeado.py
> +    def extract_date(filename: str) -> date:
**suggestion**: We don't use type hints in this project. It would be great to keep this spider following the same pattern.

2020-12-03 12:08 UTC, rennerocha commented on data_collection/gazette/spiders/rs_lajeado.py
> +        filedate = filedate.split("/")
**suggestion** If you use `dateparser` to deal with the possible variations, you will make the code simpler:

```
ipdb> dateparser.parse("1/12/17", languages=["pt"])
datetime.datetime(2017, 12, 1, 0, 0)
ipdb> dateparser.parse("14 07 17", languages=["pt"])
datetime.datetime(2017, 7, 14, 0, 0)
```

2020-12-13 20:02 UTC, meyer1994 commented
@rennerocha Applied fixes and suggestions :)

2021-01-12 16:24 UTC, meyer1994 commented
Up

2021-03-19 13:47 UTC, meyer1994 commented
Up

2021-04-19 15:54 UTC, meyer1994 commented
Up again

2021-04-19 15:55 UTC, meyer1994 commented
Up @rennerocha

2021-04-23 17:55 UTC, giuliocc requested changes
Hey @meyer1994 !

Sorry for the long wait. I have a couple of suggestions for you.

One would be capturing those gazettes with "xxxx edição do dia" in the title as `extra_edition = True` in the `Gazette` item.

The other I describe in more detail below.

Other than that I think everything is good :)

Thanks for the contribution and for the patience. It is really close to being merged don't worry :)

2021-06-08 02:33 UTC, meyer1994 commented
Now it is my time to apologize for the delay in fixing the problems. Added suggestions and modified some little things.

2021-07-02 11:54 UTC, meyer1994 commented
Up

2021-07-06 12:20 UTC, rennerocha commented
> Up

Please, don't do that! Not in this project or any other project. We are mostly volunteers and sometimes we don't have enough time to review everything or we are dealing with something with higher priority in the project during our free time.

2022-08-19 19:31 UTC, rennerocha commented
Lajeado page changed, so this spider is not working anymore. It will need a complete rewrite and no code from here can be reused, so I am closing this PR.

2022-08-19 19:31 UTC, closed without merging