Adding Sao Goncalo - RJ
okfn-brasil/querido-diario pull request #418
Opened 2021-03-04 00:54 UTC by joaopclima

2021-07-12 18:17 UTC, jaswdr commented
@joaopclima can you review this PR? I tried it locally and got this error:
```
2021-07-12 18:14:31 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <404 https://servicos.pmsg.rj.gov.br/diario_oficial>: HTTP status code is not handled or not allowed
```
It seems that the URL is wrong.

2021-07-12 18:47 UTC, joaopclima commented
Sure! I will review soon

2021-08-09 09:15 UTC, anapaulagomes requested changes
In case this isn't a portal that uses Instar, you will have to implement it for São Gonçalo's portal or we will have to close the PR. Count on us to help you with it. :)

2021-08-09 09:15 UTC, anapaulagomes commented on data_collection/gazette/spiders/rj_sao_goncalo.py
> +    start_urls = ["https://servicos.pmsg.rj.gov.br/diario_oficial"]
This page doesn't exist but this one does https://servicos.pmsg.rj.gov.br/diario_oficial.php. But after running it with this one and with https://www.saogoncalo.rj.gov.br/diario-oficial/, none are working.
By looking at other portals like http://www.altoalegre.sp.gov.br/portal/diario-oficial that also implement `BaseInstarSpider`, it seems that São Gonçalo isn't using Instar. Could you check this, please? @joaopclima

2022-09-05 22:44 UTC, rennerocha commented
Closed as stale.

2022-09-05 22:44 UTC, closed without merging