Updating Cities.md file
okfn-brasil/querido-diario pull request #441
Opened 2021-04-26 22:57 UTC by hugohfsouza

I updated the file based on the issues and PRs opened in the project.

I closed the old PR (https://github.com/okfn-brasil/querido-diario/pull/432)

I opened an issue to think about how to automate this process (https://github.com/okfn-brasil/querido-diario/issues/440)

2021-04-27 22:57 UTC, giuliocc reviewed
What do you think about discussing it first in #440 ? This will cause almost every PR adding spiders to have to solve a conflict if it is modifying the `CITIES.md` respective line. I didn't think of that before, sorry :/

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 18 | Duque de Caxias | | :soon: | [PR](https://github.com/okfn-brasil/querido-diario/pull/102) |
```suggestion
| 18 | Duque de Caxias | :soon: | | [PR](https://github.com/okfn-brasil/querido-diario/pull/102) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 22 | São Bernardo do Campo | :soon: | | [PR](https://github.com/okfn-brasil/querido-diario/pull/412) |
```suggestion
| 22 | São Bernardo do Campo | :soon: | [issue](https://github.com/okfn-brasil/querido-diario/issues/409) | [PR](https://github.com/okfn-brasil/querido-diario/pull/412) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 25 | Santo André | | :soon: | [PR](https://github.com/okfn-brasil/querido-diario/pull/286) |
```suggestion
| 25 | Santo André | :soon: | | [PR](https://github.com/okfn-brasil/querido-diario/pull/286) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 29 | Ribeirão Preto | | [issue](https://github.com/okfn-brasil/diario-oficial/issues/31) | [PR](https://github.com/okfn-brasil/querido-diario/pull/67) |
```suggestion
| 29 | Ribeirão Preto | :soon: | [issue](https://github.com/okfn-brasil/diario-oficial/issues/31) | [PR](https://github.com/okfn-brasil/querido-diario/pull/67) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 31 | Sorocaba | :soon:  | | [PR](https://github.com/okfn-brasil/querido-diario/pull/372) |
```suggestion
| 31 | Sorocaba | :soon:  | [issue](https://github.com/okfn-brasil/querido-diario/issues/314) | [PR](https://github.com/okfn-brasil/querido-diario/pull/372) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 44 | Belford Roxo | | :soon: | [PR](https://github.com/okfn-brasil/querido-diario/pull/308) |
```suggestion
| 44 | Belford Roxo | :soon: | [issue](https://github.com/okfn-brasil/querido-diario/issues/307) | [PR](https://github.com/okfn-brasil/querido-diario/pull/308) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 51 | São João de Meriti | :soon: | | [PR](https://github.com/okfn-brasil/querido-diario/pull/376) |
```suggestion
| 51 | São João de Meriti | :soon: | [issue](https://github.com/okfn-brasil/querido-diario/issues/370) | [PR](https://github.com/okfn-brasil/querido-diario/pull/376) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 86 | Taubaté | :soon:  | | |
```suggestion
| 86 | Taubaté | :soon:  | | [PR](https://github.com/okfn-brasil/querido-diario/pull/442) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 89 | Petrópolis | | :soon: | [PR](https://github.com/okfn-brasil/querido-diario/pull/282) |
```suggestion
| 89 | Petrópolis | :soon: | [issue](https://github.com/okfn-brasil/querido-diario/issues/281) | [PR](https://github.com/okfn-brasil/querido-diario/pull/282) |
```

2021-04-27 22:57 UTC, giuliocc commented on CITIES.md
> +| 90 | Camaçari | | :soon: | [PR](https://github.com/okfn-brasil/querido-diario/pull/295) |
```suggestion
| 90 | Camaçari | :soon: | [issue](https://github.com/okfn-brasil/querido-diario/issues/293) | [PR](https://github.com/okfn-brasil/querido-diario/pull/295) |
```

2021-05-03 18:53 UTC, hugohfsouza commented
@giuliocc  então, acho que aceitar seria importante pois atualiza o status das cidades  e deixamos o status atual correto. Com a automatização vamos fazer com que os próximos/novos fiquem corretos também

Uma outra preocupação é que a #440 ainda está em fase de definição enquanto novos devs vão aparecendo para contribuir com o projeto.

2021-05-11 06:05 UTC, giuliocc requested changes
Vamos só corrigir algumas tags de :soon: que ficaram na coluna de issues?

Duque de Caxias; Santo André; Belford Roxo; Petrópolis; Camaçari.

Se tiver se sentindo inspirado (sem pressão hehehe) também ficaram linhas com o PR mas sem a issue linkadas.

2021-08-09 08:04 UTC, anapaulagomes commented
Hello @hugohfsouza! Do you need any help here? :)

2022-08-01 21:02 UTC, rennerocha commented
- Update this list manually doesn't make sense.
- We can't guarantee that the PR linked to the cities will be approved, so the content is not useful to have a better vision of what will be included or not.
- We need to think a better way to know which cities exists.

2022-08-01 21:02 UTC, closed without merging