add spider for Guaira-SP
okfn-brasil/querido-diario pull request #452
Opened 2021-05-23 23:10 UTC by ilzisilva

Issue #449

2021-07-10 20:12 UTC, jaswdr requested changes
Just two comments to improve the number extraction methods, everything else LGTM

2021-07-10 20:12 UTC, jaswdr commented on data_collection/gazette/spiders/sp_guaira.py
> +        edition_number_raw = text.split(" ")[-1]
One idea to improve this method:
```
return ''.join(re.findall(r"[0-9|.]", text))
```

2021-07-10 20:12 UTC, jaswdr commented on data_collection/gazette/spiders/sp_guaira.py
> +        edition_number = ""
What should be the difference between this and the `extract_edition_number` method?

2022-09-05 22:47 UTC, rennerocha commented
Closed as stale.

2022-09-05 22:47 UTC, closed without merging