Add spider to Guaraçaí/SP
okfn-brasil/querido-diario pull request #460
Opened 2021-08-09 23:17 UTC by danielbom

Gostaria de este `pull request` fosse apenas mais uma contribuição simples para este projeto, mas infelizmente acredito que esse não será o caso. A partir da issue #459, fui levado pelo destino para selecionar a minha cidade natal, Guaraçaí. Com muita sorte e com uma pesquisa rápida no google achei o link do [diário oficial de Guaraçaí](https://imprensaoficialmunicipal.com.br/guaracai). Pronto, achei o link que precisava para obter os dados coletados pelo querido-diario. É só implementar! Foi o que fiz, mas percebi rapidamente navegando pelo site pelo "scrapy shell" que não seria tão simples assim. 

Este site é dinamicamente construído e a barra de navegação necessita esperar o código javascript para aparecer. Quando eu percebi isso, pensei: - "É só encontrar uma maneira de fazer o scrapy esperar o javascript ser executado. Fácil." Comecei a pesquisar sobre o assunto e encontrei algumas maneiras porém, possuíam a necessidade de instalar novas dependências ao projeto. 

Eu encontrei uma biblioteca chamada [scrapy_selenium](https://pypi.org/project/scrapy-selenium/) a partir de um [artigo](https://www.scrapingbee.com/blog/scrapy-javascript/) que me interessou muito porque eu conheço o selenium. Lendo outro artigo [Web Scraping With Selenium & Scrapy](https://medium.com/swlh/web-scraping-with-selenium-scrapy-9d9c2e9d83b1) comecei a procurar se existia alguma dependência no projeto que fizesse uso de alguma solução que resolvesse esse problema da construção dinâmica e como infelizmente não achei, resolvi instalar e resolver meu problema momentaneamente para poder construir uma solução para ser discutida.

Possuo algumas questões em relação a isto:

1) Vocês utilizam alguma forma de resolver o problema do carregamento dinâmico de páginas?
2) O que acham do selenium? É uma solução viável?
3) Quais soluções vocês gostariam de utilizar para resolver isto?

Bom, não espero que este `pull request` seja aceito facilmente, uma vez que conheço os problemas que depender do selenium pode trazer, sendo a principal delas a necessidade de cuidar da versão do webdriver e do navegador sendo utilizado, pois são muito sensíveis a mudanças.

A solução foi feita de forma 'genérica' para o site imprensaoficialmunicipal.com.br/{city}, uma vez que percebi que este site armazena outras cidades, sem mudar seu formato. Foi necessário modificar o arquivo "data_collection/gazette/settings.py", contudo como não conheço o `scrapy`, não sei exatamente se está realmente correto. também modifiquei o arquivo "/media/daniel/E45665A1566574E8/DISK/Materias Atuais/Software Livre/querido-diario/data_collection/requirements.in" e "data_collection/requirements.txt", uma vez que adicionei novas dependências. Não sei quem faz o gerenciamento das dependências, então não sei exatamente se está correto. Só posso dizer que o arquivo "requirements.txt" não está no 'padrão' encontrado.

2021-08-09 23:21 UTC, danielbom commented
Existem mais algumas informações que esqueci de mencionar.

Eu executei o projeto localmente e executou perfeitamente \(^.^)/. Contudo, só tenho 90% de certeza de que são estes os dados que vocês precisam, não tenho certeza sobre o valor de `power` e deixei o padrão de outros arquivos que encontrei, então gostaria de algum feedback sobre estes pontos também.

2021-08-11 16:06 UTC, anapaulagomes requested changes
Obrigada pela sua contribuição, @danielbom! 💯  Bem-vindo a bordo. Deixei alguns comentários pra você refletir e testar.

2021-08-11 16:06 UTC, anapaulagomes commented on data_collection/requirements.in
> +selenium
Prefiro que a gente tente com as alternativas citadas acima. Depois que decidirmos sobre isso, volto na revisão do código.

2021-08-11 16:07 UTC, anapaulagomes commented
Ah, importante: não esqueça de configurar o pre-commit localmente. Assim os erros de estilo mostrados no pipeline serão evitados.

2021-08-12 02:17 UTC, danielbom commented
Nice! Eu nunca pensei avaliar o código javascript para identificar estas URLs. Dei uma olhada no fluxo da rede da página e vi a resposta destas requisições. Muito inteligente.

Fiz novas atualizações removendo a dependência com o selenium e o código ficou ainda mais simples. Não precisei do FormRequest. Tentei entender, e pelo que parece precisaria ter um formulário na página, e não tem. Quem resolve estas operações é o javascript.

Em relação a formatação, fui descuidado. Não lembrei de aplicar a formação e nem instalar o pre-commit. Sorry.

Sobre criar uma issue sobre novas cidades, penso em fazer isso após completar esta implementação, quando tudo estiver certo e confirmado.

2021-08-12 02:55 UTC, danielbom reviewed
Faltava dar push nestas atualizações.

2021-08-12 02:55 UTC, danielbom commented on data_collection/gazette/spiders/base/dosp.py
> +    allowed_domains = ["dosp.com.br", "imprensaoficialmunicipal.com.br"]
Pensava em aguardar um pouco antes de coletar e criar essa issue, mas está pronta. (#461)

2021-08-12 08:49 UTC, anapaulagomes commented on data_collection/gazette/settings.py
> +from shutil import which
Esqueceu de apagar esse import aqui. Não esquece de ver sempre se o pipeline está passando ou não. Eu prefiro só revisar o código quando está tudo verde. 💚

2021-08-12 08:53 UTC, anapaulagomes commented
@danielbom pode atualizar a descrição do PR também? Assim outras pessoas vão entender melhor quando lerem as infos no futuro.

2021-08-12 16:27 UTC, danielbom commented on data_collection/gazette/settings.py
> +from shutil import which
Done.

2021-08-12 16:34 UTC, danielbom commented
> @danielbom pode atualizar a descrição do PR também? Assim outras pessoas vão entender melhor quando lerem as infos no futuro.

Poderia me explicar melhor como fazer isso? Não sei se entendi bem Sorry :/

2021-08-13 07:37 UTC, anapaulagomes commented
Era isso mesmo, @danielbom! Obrigada pela edição.

2021-08-13 07:42 UTC, anapaulagomes requested changes
Muito bom, @danielbom! 🎉 Deixei alguns comentários. Preciso da confirmação sobre a cidade antes de testar.

2021-08-13 07:42 UTC, anapaulagomes commented on data_collection/gazette/spiders/base/dosp.py
> +            file_url = "https://dosp.com.br/exibe_do.php?i=" + pdf_code
```suggestion
            file_url = f"https://dosp.com.br/exibe_do.php?i={pdf_code}"
```

2021-08-13 07:42 UTC, anapaulagomes commented on data_collection/gazette/spiders/sp_guaracai.py
> +    allowed_domains = ["glicerio.sp.gov.br"]
Essa implementação é para Glicerio ou para Guaraçaí? 😅

2021-08-13 13:41 UTC, danielbom commented on data_collection/gazette/spiders/sp_guaracai.py
> +    allowed_domains = ["glicerio.sp.gov.br"]
Ops... Problemas de (Ctrl + C) > (Ctrl + V)...

2021-08-13 13:50 UTC, anapaulagomes commented on data_collection/gazette/spiders/sp_guaracai.py
> +    allowed_domains = ["glicerio.sp.gov.br"]
Pode, por favor, remover essa linha então?

2021-08-13 13:53 UTC, danielbom commented on data_collection/gazette/spiders/sp_guaracai.py
> +    allowed_domains = ["glicerio.sp.gov.br"]
Done.

2021-08-17 07:02 UTC, anapaulagomes approved these changes
Good to go! 🚀

2021-08-17 07:02 UTC, merged