Sp sao sebastiao
okfn-brasil/querido-diario pull request #469
Opened 2021-08-23 23:40 UTC by fvessoni

Issue #468

2021-12-06 14:58 UTC, anapaulagomes requested changes
Olá, @fvessoni! Obrigada pela sua contribuição. Executei o spider e ele funcionou corretamente. ✨  Precisamos fazer alguns ajustes no código (melhorias). Qualquer dúvida é só falar.

2021-12-06 14:58 UTC, anapaulagomes commented on data_collection/gazette/spiders/sp_sao_sebastiao.py
> +import datetime as dt
```suggestion
from datetime import date, datetime
```
Dessa forma o código fica mais legível e segue os padrões de outros imports no projeto.

2021-12-06 14:58 UTC, anapaulagomes commented on data_collection/gazette/spiders/sp_sao_sebastiao.py
> +            # edition_date = edition.split("_")[4]
Pode, por favor, remover esses comentários? No momento eles não têm muita utilidade para o código do Spider.

2021-12-06 14:58 UTC, anapaulagomes commented on data_collection/gazette/spiders/sp_sao_sebastiao.py
> +                parsed_date = dt.datetime.strptime(
Você pode usar a biblioteca `dateparser` para facilitar o parseamento da data.

https://github.com/okfn-brasil/querido-diario/blob/86004049c6eee305e13066cf3607d30849bb099a/data_collection/gazette/spiders/base/doem.py#L77

2021-12-06 14:58 UTC, anapaulagomes commented on data_collection/gazette/spiders/sp_sao_sebastiao.py
> +                self.logger.warning("INVALID DATE: ||%s||", edition)
Para facilitar, podemos seguir o mesmo padrão de outros logs com f-strings e lower case:

```suggestion
                self.logger.warning(f"Invalid date {edition}")
```

2021-12-06 14:58 UTC, anapaulagomes commented on data_collection/gazette/spiders/sp_sao_sebastiao.py
> +    start_date = dt.date(2017, 3, 15)
Seria bom adicionar o `end_date` também. Caso seja o site utilizado atualmente, o valor padrão é `None`.

2021-12-08 10:47 UTC, anapaulagomes commented
Ah, mais uma coisa: pode atualizar o [CITIES.md](https://github.com/okfn-brasil/querido-diario/blob/main/CITIES.md), por favor?

2021-12-14 18:15 UTC, fvessoni commented
oi @anapaulagomes ! Obrigado pelas correções, veja se agora ficou melhor. Apanhei tanto do git hoje, que eu sei lá se foi certo.. (rsrs).

2022-09-20 01:58 UTC, rennerocha commented
Closed as stale.

2022-09-20 01:58 UTC, closed without merging