add prudentopolis spider
okfn-brasil/querido-diario pull request #474
Opened 2021-08-31 03:42 UTC by mvgolom

Issue #473

2021-12-08 10:45 UTC, anapaulagomes requested changes
Ótimo trabalho aqui, @mvgolom! 💯  Rodei o spider e rodou bem e sem erros.
Deixei algumas sugestões mas nada complexo. Qualquer dúvida é só falar.

2021-12-08 10:45 UTC, anapaulagomes commented on data_collection/gazette/spiders/pr_prudentopolis.py
> +            parse(date, languages=["pt"]).date()
Ao invés de fazer um segundo loop aqui, você poderia manter esse trecho dentro do `for` anterior.

2021-12-08 10:45 UTC, anapaulagomes commented on data_collection/gazette/spiders/pr_prudentopolis.py
> +    start_date = datetime.date(2010, 5, 27)
Pode adicionar a `end_date` também? 🙏🏽

2021-12-08 10:45 UTC, anapaulagomes commented on data_collection/gazette/spiders/pr_prudentopolis.py
> +            url = relative_url.xpath("td[4]/a/@href").extract()[0]
A lib parsel sugere o uso de `get()` and `getall()` ao invés do extract(). Nesse caso você poderia fazer:

```suggestion
            url = relative_url.xpath("td[4]/a/@href").get()
```

2021-12-08 10:47 UTC, anapaulagomes commented
Ah, mais uma coisa: pode atualizar o [CITIES.md](https://github.com/okfn-brasil/querido-diario/blob/main/CITIES.md), por favor?

2022-09-20 01:58 UTC, rennerocha commented
Closed as stale.

2022-09-20 01:58 UTC, closed without merging