Add ma_caxias spider
okfn-brasil/querido-diario pull request #504
Opened 2021-10-24 14:48 UTC by alenvieira

Adds a new crawler from my hometown to the project.

Close #503

2022-03-14 23:24 UTC, giuliocc requested changes
### Português

@alenvieira o raspador precisava de uns ajustes pra cobrir alguns casos de fronteira e também para dar uma desacelerada na raspagem pois o servidor não aguenta. Atualizei sua branch com a main e fui explicando as modificações através dos commits que fiz [num PR no seu fork](https://github.com/alenvieira/querido-diario/pull/1).

Gostaria de integrar Caxias na plataforma de produção do QD. Me diz aí o que acha das sugestões e logo menos poderemos consultar ter sua cidade na plataforma! <3

### English

@alenvieira the spider needed some adjustments to cover some edge cases e also some throttling because the server couldn't handle the rate of requests. I updated your branch with main and explained the needed modifications throughout the commits I made in [a PR in your fork](https://github.com/alenvieira/querido-diario/pull/1).

I'd like to put Caxias in QD's production platform. Tell me what you think about the suggestions and very very soon we can have your hometown in the platform! <3

2022-03-15 01:08 UTC, alenvieira commented
@giuliocc Excelentes contribuições! Muito contente em saber que Caxias pode ir em breve para a plataforma. :D

2022-03-18 16:01 UTC, giuliocc approved these changes
### Português

Que ótimo @alenvieira ! Vamo simbora!

### English

That's great @alenvieira ! Let's go!

2022-03-18 16:02 UTC, giuliocc commented
LGTM!

![_](https://media.giphy.com/media/7frSUXgbGqQPKNnJRS/giphy.gif)

2022-03-18 16:02 UTC, merged