add ma_buriti_bravo spider
okfn-brasil/querido-diario pull request #525
Opened 2021-11-08 02:35 UTC by alenvieira

Adds a new crawler to the project.

Close #524

2021-12-15 19:00 UTC, anapaulagomes requested changes
Obrigada pela contribuição, @alenvieira! 🎉 O spider rodou certinho por aqui. Deixei alguns comentários para melhorar o código.

Além disso, pode adicionar a cidade ao arquivo [CITIES.md](https://github.com/okfn-brasil/querido-diario/blob/main/CITIES.md), por favor?

2022-03-15 00:46 UTC, alenvieira commented on data_collection/gazette/spiders/ma_buriti_bravo.py
> +        for page in range(0, last_page):
Feito!

2022-03-15 00:47 UTC, alenvieira commented on data_collection/gazette/spiders/ma_buriti_bravo.py
> +                date = datetime.strptime(line.xpath("td[3]/text()").get(), "%d/%m/%Y")
Troquei o nome da variável date para date_gazette porque já importo o date que provavelmente estava sendo sobrescrito.

2022-03-15 00:48 UTC, alenvieira commented on data_collection/gazette/spiders/ma_buriti_bravo.py
> +                url=response.url, method="POST", formdata={"pag": str(page)}
Feito!

2022-03-15 00:49 UTC, alenvieira commented on data_collection/gazette/spiders/ma_buriti_bravo.py
> +    def start_requests(self):
Pelo que entendi, também tem que colocar o callback no parse para o parse_page.

2023-03-07 23:50 UTC, rennerocha commented
Stale pull request.

2023-03-07 23:50 UTC, closed without merging