FECAM spider update and new model field
okfn-brasil/querido-diario pull request #530
Opened 2021-12-15 01:42 UTC by jvanz

Update the spider to crawl the FECAM website and add a new field in the model.

2021-12-21 00:29 UTC, anapaulagomes requested changes
Massa! Preciso rodar ainda mas já deixei algumas considerações.

Sobre o novo campo: em qual Pipeline ele seria utilizado?

2021-12-21 00:29 UTC, anapaulagomes commented on data_collection/gazette/spiders/base/fecam.py
> +        for i in range(1, self.get_last_page(response) + 1):
```suggestion
        for page in range(1, self.get_last_page(response) + 1):
```

2022-01-22 23:28 UTC, jvanz commented
> Massa! Preciso rodar ainda mas já deixei algumas considerações.
> 
> Sobre o novo campo: em qual Pipeline ele seria utilizado?

Estou estudando  a aplicação de algumas técnicas de NLP e transferência de estilo com os textos dos diários e essa informação seria útil para filtrar o tipo de dados que quero trabalhar e utilizar nos possíveis modelos. 

Porém, durante os últimos dias vi que o site de FECAM mudou como publica dos diários. Agora eles também tem um arquivo único para todos os municípios. O que é desperdício de espaço colocar para rodar esse spider em produção sem tratar esse problema. Por isso, vou colocar isso como draft por hora.

2022-01-22 23:29 UTC, jvanz commented on data_collection/gazette/database/models.py
> +    # processing pipeline. Some website (e.g. fecam) allow the user to filter
More info about the field at : https://github.com/okfn-brasil/querido-diario/pull/530#issuecomment-1019376404

2023-03-07 23:50 UTC, rennerocha commented
Stale pull request.

2023-03-07 23:50 UTC, closed without merging