Create rj_barra_mansa.py
okfn-brasil/querido-diario pull request #563
Opened 2022-05-16 23:24 UTC by alexandreandrade1

add spider Barra Mansa - RJ

2025-02-20 12:39 UTC, firefueled requested changes
Opa camarada!
Parece que esta PR ainda não foi finalizada porque faltam algumas coisas nela que precisamos antes de validar a entrega.
Veja meus comentários abaixo.

Será que consegue terminá-la?

2025-02-20 12:41 UTC, firefueled commented
Outra coisa, também precisamos de evidências de execução correta em formato de arquivos de log e csv.
Dê uma olhadinha [nesta página](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html) para ver o que pedimos para aceitar uma PR.

2025-04-20 19:27 UTC, trevineju approved these changes
oi, @alexandreandrade1, obrigada pela contribuição! (e @firefueled pela revisão <3) 

Precisava dessa PR para tratar os casos de Barra Mansa relacionados à #1389, então finalizei os ajustes que faltavam. Testes:
[rj_barra_mansa_completa.csv](https://github.com/user-attachments/files/19826767/rj_barra_mansa_completa.csv) | [rj_barra_mansa_completa.log](https://github.com/user-attachments/files/19826768/rj_barra_mansa_completa.log)
[rj_barra_mansa_periodo.log](https://github.com/user-attachments/files/19826769/rj_barra_mansa_periodo.log) | [rj_barra_mansa_periodo.csv](https://github.com/user-attachments/files/19826770/rj_barra_mansa_periodo.csv)
[rj_barra_mansa_ultima.log](https://github.com/user-attachments/files/19826771/rj_barra_mansa_ultima.log) | [rj_barra_mansa_ultima.csv](https://github.com/user-attachments/files/19826772/rj_barra_mansa_ultima.csv)


Quando você começou a PR, Alexandre, ainda não tínhamos uma boa documentação no projeto, mas agora temos. Se quiser continuar contribuindo, fica a sugestão de leitura de apoio/consulta: https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html

2025-04-22 18:27 UTC, firefueled approved these changes

2025-04-28 03:06 UTC, merged