Add Belford Roxo-RJ spider
okfn-brasil/querido-diario pull request #658
Opened 2022-09-30 23:52 UTC by ayharano

resolve okfn-brasil/querido-diario#629

2022-10-04 00:32 UTC, rennerocha requested changes

2022-10-04 00:32 UTC, rennerocha commented on data_collection/gazette/spiders/rj_belford_roxo.py
> +                return
**sugestão** Ao dar `return` aqui, você interrompe o seu loop. Se as datas não vierem ordenadas, você pode perder algum Diário. Um `continue` (para você só ignorar esse item) seria um pouco mais seguro.

**problema** Você está verificando apenas `start_date`. Você também precisa verificar `end_date` pois podemos estar pedindo apenas um período específico.

2022-10-04 02:57 UTC, ayharano commented on data_collection/gazette/spiders/rj_belford_roxo.py
> +                return
Conforme solicitado, fiz as alterações mencionadas modificando o `if` indicado e seu conteúdo:

```python
            if gazette_date < self.start_date or self.end_date < gazette_date:
                continue
```

Fiz um force push com um único commit já tratando tanto a substituição de `return` por `continue` assim como o tratamento de `end_date`.

2022-10-18 21:36 UTC, rennerocha approved these changes
O spider está funcionando perfeitamente. Fiz duas pequenas modificações:
- Removi um request desnecessário (`gazette_url` já é suficiente para fazer o download do arquivo)
- Adicionei o `edition_number` que está disponível nos dados retornados

2022-10-18 21:36 UTC, merged