Ajusta Mossoro-RN
okfn-brasil/querido-diario pull request #861
Opened 2023-05-29 15:12 UTC by trevineju

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição
O raspador pra Mossoró está coletando o HTML da página intermediária do site publicador e não o PDF de fato.

2023-08-15 20:45 UTC, claromes commented
Revisando esse PR.

2023-08-17 21:15 UTC, claromes requested changes
@trevineju Ju, o código está correto e agora o retorno são os diários em PDF (incluindo os argumentos de start e end date). Adicionei dois comentários só pra padronizar o código.

Além disso, na linha 13, o dia de início é 2 (não consegui adicionar comentário nessa linha do código).

Obrigada.

2023-08-17 21:15 UTC, claromes commented on data_collection/gazette/spiders/rn_mossoro.py
> +            '//div[@id="main-content"]//li[3]//strong/text()'
Padronizar com aspas duplas (como na linha 35)

2023-08-17 21:15 UTC, claromes commented on data_collection/gazette/spiders/rn_mossoro.py
> +            '//div[@id="main-content"]//a[contains(@href, "/pmm/uploads/publicacao/pdf")]/@href'
Padronizar com aspas duplas (como na linha 35)

2023-08-23 13:27 UTC, ogecece requested changes
Reforço os comentários da @claromes nessa revisão também.

Talvez pareça estranho as strings com aspas simples terem passado pelo `black` mas apesar de [preferir as strings com aspas duplas por padrão](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings), se aspas simples forem utilizadas e o conteúdo da string tiver aspas duplas ele não vai mexer automaticamente.

De resto, também testei aqui e as 161 edições esperadas foram baixadas e eram PDFs: 
[output.csv](https://github.com/okfn-brasil/querido-diario/files/12419593/output.csv)
[crawl.log](https://github.com/okfn-brasil/querido-diario/files/12419594/crawl.log)

2023-08-23 13:27 UTC, ogecece commented on data_collection/gazette/spiders/rn_mossoro.py
> +                f"https://www.dom.mossoro.rn.gov.br{intermediary_page}",
A gente está usando bastante a base da url e completando com o path relativo na mão. Seria bom evitar essa repetição.

Uma dica seria usar `response.urljoin()` para não precisar deixar o domínio hard-coded
```suggestion
                response.urljoin(intermediary_page),
```
Também vale pras linhas 39 e 54

2023-08-23 13:27 UTC, ogecece commented on data_collection/gazette/spiders/rn_mossoro.py
> +        edition_number = re.search(r"\d+", raw_edition_number).group(0)
O `0` pode ser omitido e diria que até melhora um pouco a legibilidade

```suggestion
        edition_number = re.search(r"\d+", raw_edition_number).group()
```

2023-08-23 13:27 UTC, ogecece commented on data_collection/gazette/spiders/rn_mossoro.py
> +        edition_number = re.search(r"\d+", raw_edition_number).group(0)
Depois de ver os outputs fui dar uma olhada nas edições com valores repetidos: 83, 98 e 121.

As edições publicadas no fim de semana deveriam ser 83A, 98A e 121A como aparece no site.

Então na verdade não precisamos de regex aqui para identificar apenas os dígitos. O texto do elemento já é o número da edição.

Em paralelo, essas edições que não são apenas dígitos são edições extras.

2023-09-19 13:34 UTC, trevineju commented on data_collection/gazette/spiders/rn_mossoro.py
> +        edition_number = re.search(r"\d+", raw_edition_number).group(0)
> Em paralelo, essas edições que não são apenas dígitos são edições extras.

Enderecei isso adicionando um novo método `extra_edition_check()`
Ia chamar de `_is_extra_edition` já que retorna um booleano, porém como `is_extra_edition` já é um campo de Gazette, troquei.

2023-09-19 14:36 UTC, trevineju commented
ah, aliás, só teve uma modificação que fiz pr'além das solicitadas: `power="executive"` (antes era `executive_legislative`) 

O diário nesse novo site vem assinado com a mensagem abaixo. Por isso, entendi que não mais tem a confusão de executivo e legislativo nos atos oficiais, agora vai ser apenas executivo mesmo 
(o projeto de lei mencionado é de dez/22, e o site do diário mudou em jan/23; essa regularização deve ter sido o motivo): 
> Diário Oficial de Mossoró é uma publicação da Prefeitura Municipal de Mossoró, Instituído pela
lei [N.º 4.003/2022](https://dom.mossoro.rn.gov.br/dom/legislacao), Coordenado pela Secretaria Municipal de Governo e dirigido pela Secretaria Municipal de Comunicação Social.

2023-10-17 17:31 UTC, merged