Adiciona raspador para Barreiras-BA
okfn-brasil/querido-diario pull request #863
Opened 2023-05-31 23:04 UTC by trevineju

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [] Você verificou que não existe nenhum erro nos logs (`log/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

resolve #862 

Validei os erros. Só não marquei o item na checklist, pois há erros, mas não por conta do raspador. 
Algumas páginas de diários estão vazias, por exemplo: http://www.barreiras.ba.gov.br/diario/pdf/diario924.pdf

2023-07-06 16:17 UTC, ogecece requested changes
Testei aqui ([logs.txt](https://github.com/okfn-brasil/querido-diario/files/11970255/logs.txt)) e tive 38 `DroppedItem` por conta da URL não conter o documento. Tentei acessar alguns e não existiam como a @trevineju apontou então faz sentido não travar o raspador por conta de problema no sistema publicador.

Deixei poucos comentários no parsing. No geral está muito bom!

2023-07-06 20:26 UTC, trevineju commented on data_collection/gazette/spiders/ba_barreiras.py
> +        editions = response.xpath('//*[@class="style16"]')
@ogecece, nesse caso essa alteração diminui a coleta, pq não são todas as vezes que o elemento `span` está aninhado nessa `div` específica. Lembra que tentei fazer vários formatos desse raspador? Esse era um dos problemas nas páginas mais antigas (a partir de 2011 parece estabilizar). 

Rodei esse raspador aqui, ignorando o download dos arquivos, simulando que o parse() apenas vê quantos elementos do seletor tem na página: 
~~~
    def parse(self, response):
        editions = response.xpath()
        print(response.url, "    ", len(editions))
~~~
 
 Tive esse resultado:
 A primeira execução foi como enviei o PR e a segunda com a sua modificação. Veja que os anos de 2008 a 2010 tem diferenças. A partir de 2011, não. 
 
![image](https://github.com/okfn-brasil/querido-diario/assets/44185775/b7740a66-ce87-4e44-b5fd-fb9b946d9a3a)

2023-07-06 20:43 UTC, trevineju commented on data_collection/gazette/spiders/ba_barreiras.py
> +                is_extra_edition=True if "extra" in metadata_str.lower() else False,
feito!

2023-07-06 22:53 UTC, ogecece commented on data_collection/gazette/spiders/ba_barreiras.py
> +        editions = response.xpath('//*[@class="style16"]')
Entendi! Fui conferir aqui quais diferenças estavam acontecendo e testar outras alternativas. Podemos manter o tipo do elemento genérico mas pelo que vi dá pra fixar a `div`.

Vi que a edição 958 em 2009 não estava sendo capturada pois tinha outra classe além da `style16`. Nesse caso é melhor a gente mudar pra css que a sintaxe vai ficar mais limpa.

O que acha?
```suggestion
        editions = response.css('div.content .style16')
```

2023-07-07 22:35 UTC, trevineju commented on data_collection/gazette/spiders/ba_barreiras.py
> +        editions = response.xpath('//*[@class="style16"]')
Havia aceito esta sugestão, porém houve um conflito com o formatador `black`. A mudança foi acolhida manualmente.

2023-07-13 15:33 UTC, ogecece requested changes
Shou! Pode adicionar no `enabled_spiders`?

2023-07-13 21:22 UTC, ogecece approved these changes
LGTM!

2023-07-13 21:24 UTC, merged