adiciona spider timon-ma
okfn-brasil/querido-diario pull request #886
Opened 2023-06-19 20:31 UTC by peddrogomes

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [X] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [X] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [ ] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [X] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [X] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

Resolve issue: #869 

- Na primeira pagina é possível obter todas as paginas que existe, dessa forma a função get_pages() nos retorna uma lista com todos os links.
- Depois disso é só interar na lista de links e pegar cada diario. 😄

2023-09-04 21:22 UTC, Winzen commented
Olá @peddrogomes, Tudo bem?

Muito obrigado pela contribuição🎉

Será iniciado aqui o processo de revisão dupla que estamos adotando no GT de Raspadores ([saiba mais](https://docs.google.com/document/d/1fnDOBpzqi_m3VBVkJ8u8CjMxOk5Za75kD3CH9yEaff0/edit#heading=h.99bxqsylnnu)) para familiarizar as pessoas com o processo.

Eu serei o primeiro revisor.
Peço que só faça qualquer alteração ao seu PR, depois que o segundo revisor ter concluído também.

Segundos revisores podem ser: @ogecece  ou @trevineju

2023-09-04 21:28 UTC, Winzen commented on data_collection/gazette/spiders/ma_timon.py
> +    start_urls = ["https://timon.ma.gov.br/semgov/diario/listagem.php"]
Infelizmente parece que ouve mudanças onde eles estão guardando os diários e esse link acabou ficando obsoleto. 😢

2023-09-04 21:30 UTC, Winzen commented on data_collection/gazette/spiders/ma_timon.py
> +    start_urls = ["https://timon.ma.gov.br/semgov/diario/listagem.php"]
```py
start_urls = ["https://timon.ma.gov.br/semgov/diario/listagem.php"]
```
Infelizmente parece que ouve mudanças onde eles estão guardando os diários e esse link acabou ficando obsoleto. 😢

2023-09-04 21:33 UTC, Winzen commented
Com a mudança do site. Acabei verificando que o resto do código não consegue mais coletar os diários devidamente

2023-09-04 21:41 UTC, Winzen commented
Os diários agora estão localizados em https://timon.ma.gov.br/diario/ 

Verificando o novo site vi que se você mandar um `POST` para https://timon.ma.gov.br/diario/pesquisa_numerodiario.php com o parâmetro de `inputDiario: "1"` você consegue uma pagina com a lista de todos os diários disponíveis.

Acredito que isso possa facilitar adaptação do código ao novo site

2023-09-04 21:52 UTC, Winzen requested changes
Com essa questão da mudança de site onde os diários são alojados. Não irei mais fundo na revisão.

Peço que espere a confirmação do segundo revisor para prosseguir.
Agradeço de novo pela contribuição e sinto pela mudança do site  😢 

@ogecece @trevineju

2023-09-05 19:54 UTC, trevineju commented
É isso aí. Obrigada por verificar @Winzen! 

@peddrogomes você pretende voltar a trabalhar este PR para o novo site de Timon-MA?

2023-09-05 21:32 UTC, trevineju commented
Como o site mudou e o código não é mais vigente, estou fechando este PR. 
@peddrogomes se você quiser continuar trabalhando na cidade, pode avisar lá na issue #869 😃

2023-09-05 21:32 UTC, closed without merging