Adiciona base AdminLTE e suas cidades
okfn-brasil/querido-diario pull request #892
Opened 2023-06-19 23:51 UTC by claromes

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

- Adiciona spider base para o AdminLTE (#871 )
- Adiciona spider para Gurupi-TO (base AdminLTE) (#878 )
- Adiciona spider para Santana do Araguaia-PA (base AdminLTE) (#879)

2023-06-20 04:18 UTC, Winzen commented
Enquanto eu verificava como eu iria pegar as ultimas datas para fazer automação de outros municípios com a sua class.

Notei uma url padrão onde eles fazem as requisições com informações dos diários do mês e uma para saber os anos validos que os diários tem.

Exemplo:

Com esse ==> https://www.adolfo.sp.gov.br/portal/calendario/diario_oficial/anos/
Pegamos os anos que estão disponíveis para coleta a partir de um JSON


Com esse ==> https://www.adolfo.sp.gov.br/portal/calendario/diario_oficial/1/2020/
Trocando o ano e o mês no link recebemos um JSON com se há diários disponíveis para a data requisitada, dia, link e edição dos diários do mês solicitado.

Aparamente isso se aplica para todos os links desse sistema.

Não sei se você chegou a notar isso também. Mas vou deixar isso aqui caso ache útil. 😉

2023-06-22 19:23 UTC, anapaulagomes requested changes
Obrigada pela sua contribuição, @claromes! 🎉 🏆 Boas-vindas ao projeto!

Deixei algumas sugestões menores. Mas antecipo que testei e está tudo funcionando direitinho. Muito bom!

2023-06-22 19:23 UTC, anapaulagomes commented on data_collection/gazette/spiders/to_gurupi.py
> +    file_url_column = 6
Os valores são iguais nos dois spiders adicionados. Tem evidências de que seria diferente em outros? Além disso, nos dois essa coluna é a última da tabela. Sugiro mudar para pegar sempre a última coluna ao invés de ter esse valor hard-coded (reduz as chances de erros se essa suposição estiver correta).

2023-06-23 13:15 UTC, anapaulagomes commented on data_collection/gazette/spiders/base/adminlte.py
> +class AdminlteGazetteSpider(BaseGazetteSpider):
Sim!

2023-08-08 20:12 UTC, claromes commented
@anapaulagomes Ajustes feitos ;)

2023-08-15 21:29 UTC, anapaulagomes commented
Oi, @claromes! Valeu pelos ajustes :) Rodei o crawler de `` e deu tudo certo. Até uns itens extras foram coletados! Mas o `pa_santana_do_araguaia` não está rodando e quando acessei o site estava fora do ar. Você consegue acessar o https://diariooficial.pmsaraguaia.pa.gov.br/? Como está funcionando a raspagem localmente?

2023-08-15 22:04 UTC, trevineju commented
Cliquei aqui e realmente o site está fora do ar. Hoje, o Brasil passou por um [blecaute](https://exame.com/brasil/apagao-de-energia-e-o-maior-do-pais-desde-2009-relembre-outros-blecautes/) e vários sites cairam. Tive problemas também com outros casos. Podemos esperar uns dias e tentar de novo

2023-08-15 22:08 UTC, claromes commented
@anapaulagomes Está fora mesmo. Quando eu ajustei estava tudo ok. Podemos aguardar, como a @trevineju disse.

2023-08-16 14:35 UTC, claromes commented
@anapaulagomes  Oi, Ana. O site de Santana do Araguaia voltou.

2023-08-16 16:50 UTC, trevineju commented
ihuu! Como @anapaulagomes validou ontem e o site de Santana do Araguaia voltou hoje, já validei aqui essa parte que faltava.  🥳 

Obrigada @claromes pelo PR e @anapaulagomes pela revisão ❤️ Vocês são maravilhosas 🚀

<img src="https://media3.giphy.com/media/3oKIPyRuDfitoVWPWE/giphy.gif"/>

2023-08-16 16:50 UTC, trevineju approved these changes

2023-08-16 16:51 UTC, trevineju commented
Adicionei um commit habilitando em produção.  

Precisei atualizar a branch com as novas modificações da main e no processo tive que renomear os commits pq o caracter # é um caracter de comentário, então o commit ficava vazio aqui. (Os commits originais começavam com #891 que é a issue que Claromes atacou, apenas retirei esse trecho da mensagem). 

![Screenshot from 2023-08-16 13-37-17](https://github.com/okfn-brasil/querido-diario/assets/44185775/5168cdaa-4b89-4281-bfda-9f3b6ed139d0)

2023-08-16 16:52 UTC, merged

2023-08-16 16:55 UTC, claromes commented
@trevineju Obrigada! Vou ficar de olho no uso do `#` no início das mensagens.