Add extension
okfn-brasil/querido-diario pull request #946
Opened 2023-09-30 07:48 UTC by Winzen

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

PR referente #819

Fiz o levantamento que de **250478** diários raspados,  **53,95%** deles que equivale a um total de **135139** diários, estão sem extensão e como já foi descrito em #819 é um problema para os usuários do Windows.
Dados levantados ➡️ [Dados](https://docs.google.com/spreadsheets/d/1-otBxgWGeg58lbbsfKl9ZUoTz1quREPK/edit#gid=328086594)

Escolhi 5 dos municípios com mais diários sem extensão para fazer os teste: `Cuiabá`, `Santos`, `Rio de Janeiro`, `Santo André` e `Belém`.
![image](https://github.com/okfn-brasil/querido-diario/assets/94500122/232e0714-3209-49ab-aeee-cddbe4ec086a)

#

Primeiro testei eles sem o validador de extensão, para confirmar que eles não estavam sendo armazenados com `.pdf`.
Segui os logs confirmando a falta de extensão:
[log_pa_belem_sem_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774154/log_pa_belem_sem_extensao.txt)
[log_rj_rio_de_janeiro_sem_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774155/log_rj_rio_de_janeiro_sem_extensao.txt)
[log_sp_santo_andre_sem_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774156/log_sp_santo_andre_sem_extensao.txt)
[log_sp_santos_sem_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774157/log_sp_santos_sem_extensao.txt)
[log_mt_cuiaba_sem_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774158/log_mt_cuiaba_sem_extensao.txt)

Como vemos em todos os registros dos logs o `path` está sem extensão.
Exemplo: `'path': '5103403\\2023-09-04\\ebb9ca864c1569b7cdb25e599e00a49b77d38b4c'`

#

Agora segue os mesmo rapadores, com o validador colocado na `pipelines.py`.
Logs:
[log_pa_belem_com_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774161/log_pa_belem_com_extensao.txt)
[log_rj_rio_de_janeiro_com_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774162/log_rj_rio_de_janeiro_com_extensao.txt)
[log_sp_santo_andre_com_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774163/log_sp_santo_andre_com_extensao.txt)
[log_sp_santos_com_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774164/log_sp_santos_com_extensao.txt)
[log_mt_cuiaba_com_extensão.txt](https://github.com/okfn-brasil/querido-diario/files/12774165/log_mt_cuiaba_com_extensao.txt)

Vemos que agora todos eles estão com extensão correta em `path`.
Exemplo: `'path': '5103403\\2023-09-04\\ebb9ca864c1569b7cdb25e599e00a49b77d38b4c.pdf',`

#

E para finalizar fiz teste com 5 dos municípios com mais diários que estão com extensão corretamente: `Porto Alegre`, `Goiânia`, `Manaus`, `Salvador` e `Natal`
![image](https://github.com/okfn-brasil/querido-diario/assets/94500122/52ac9a78-9972-4326-9640-7d6d2a8ba6f7)

Segue os logs:

[log_rn_natal.txt](https://github.com/okfn-brasil/querido-diario/files/12774181/log_rn_natal.txt)
[log_rs_porto_alegre.txt](https://github.com/okfn-brasil/querido-diario/files/12774182/log_rs_porto_alegre.txt)
[log_am_manaus.txt](https://github.com/okfn-brasil/querido-diario/files/12774183/log_am_manaus.txt)
[log_ba_salvador.txt](https://github.com/okfn-brasil/querido-diario/files/12774184/log_ba_salvador.txt)
[log_go_goiania.txt](https://github.com/okfn-brasil/querido-diario/files/12774185/log_go_goiania.txt)

Vemos que eles se encontram sem erros e com as extensão ainda correta, mesmo com o validador já inserido a `pipelines.py`.

# 

**Obs:** Acredito que tenha forma mais "legante" de fazer essa validação que posteriormente poderia ser aplicada. Mas já deixo o PR até eu ver isso e a ideia se alguém tiver uma melhor abordagem. 
Por algum motivo o meu `settings.py` acabou diferente do "main" faço a alteração caso necessário.

2023-10-01 20:37 UTC, trevineju commented
@Winzen será que você conseguiria atualizar a história dos commits? 
Se você navegar no repositório, voltar pra branch principal (`git checkout main`) e atualizar sua main local com a main do repositório (`git fetch`, `git pull`). Com a main local atualizada, você não precisa criar um merge ( [aquele fc80 que aparece aqui](https://github.com/okfn-brasil/querido-diario/pull/946/commits) ), bastaria voltar para a branch deste PR (`git checkout add_extension`) e aí usa `git rebase main`. Se tudo der certo, vc vai perceber que os commits meus e do Renne vão sair deste histórico, ficando apenas os teus. Vai precisar forçar (`git push -f`) para enviar as modificações de volta pra cá

2023-10-03 23:43 UTC, ogecece requested changes
@Winzen removi o commit extra do PR e venho fazer uma sugestão sobre como continuar esse PR.

Vejo que o caminho seria detectar a extensão do arquivo baixado, caso ele não seja informado. Já utilizamos a biblioteca [`python-magic`](https://github.com/ahupp/python-magic) aqui e tivemos problemas com versões da `libmagic`. Recentemente tive contato com a [`filetype`](https://github.com/h2non/filetype.py), que não depende da `libmagic` e poderia ser uma alternativa interessante.

Não consigo trabalhar nisto no momento nem testar extensivamente, mas venho aqui com uma proposta que você poderia trabalhar em cima, utilizando a `filetype`:

```python
    def file_path(self, request, response=None, info=None, item=None):
        """
        Path to save the files, modified to organize the gazettes in directories.
        The files will be under <territory_id>/<gazette date>/.
        """

        filepath = super().file_path(request, response=response, info=info, item=item)
        # The default path from the scrapy class begins with "full/". In this
        # class we replace that with the territory_id and gazette date.
        datestr = item["date"].strftime("%Y-%m-%d")
        filename = Path(filepath).name
        extension = Path(filepath).suffix

        if not extension and response is not None:
            filename += f".{self._detect_extension(response)}"

        return str(Path(item["territory_id"], datestr, filename))

    def _detect_extension(self, response):
        """Checks file extension from file header if possible"""
        max_file_header_size = 261
        file_kind = filetype.guess(response.body[:max_file_header_size])
        if file_kind is None:
            raise Exception("Couldn't detect file type")  # Provavelmente seria melhor um log de warning
        
        return file_kind.extension
```

Essa modificação no pipeline provavelmente permitiria que a detecção de extensões fosse feita corretamente.

Porém, um problema surge pois o `self.file_path` também é utilizado para verificar se o arquivo já foi baixado para evitar baixá-lo novamente, e neste ponto não temos a response para detectar a extensão e montar o caminho corretamente.

Ou seja, nos casos onde forçamos a detecção da extensão, o arquivo sempre seria baixado novamente de forma desnecessária.

Documentações relevantes: [1](https://doc.scrapy.org/en/latest/topics/media-pipeline.html?highlight=files%20pipeline#module-scrapy.pipelines.files) e [2](https://doc.scrapy.org/en/latest/_modules/scrapy/pipelines/files.html)

Também vale investigar mais a fundo outras possíveis consequências. Mas inicialmente não vejo tanto problema se a solução mais simples só tivesse essa consequência.

Outras alternativa seria construirmos uma [extensão pro Scrapy](https://doc.scrapy.org/en/latest/topics/extensions.html#writing-your-own-extension) ou disponibilizar um script pros usuários (talvez pela [querido-diario-toolbox](https://github.com/okfn-brasil/querido-diario-toolbox), ambas as alternativas (a primeira, automaticamente, e a segunda de acordo com o desejo de quem for usar o projeto) precisariam corrigir tanto o banco quando o sistema de arquivos.

2023-10-07 10:34 UTC, rennerocha commented on data_collection/gazette/pipelines.py
> +        if not filename.count(".pdf"):
**problema** **Só** a extensão não indica se o arquivo é ou não é um PDF válido. Se queremos verificar isso em algum momento, é necessário analisar o conteúdo do arquivo. [Aqui](https://stackoverflow.com/questions/559096/check-whether-a-pdf-file-is-valid-with-python_) e [aqui](https://pypi.org/project/filetype/) temos algumas possibilidades. Porém é necessário analisar o impacto disso no processamento geral.

Outro problema é que existem cidades que fornecem o arquivo em outros formatos (como .docx). Sua solução vai adicionar erroneamente a extensão .pdf nesses arquivos.

2024-06-03 20:16 UTC, ogecece commented
Fechando o PR em razão da implementação de #1153

2024-06-03 20:16 UTC, closed without merging