[DOSP]Grupo 2 de spiders
okfn-brasil/querido-diario pull request #955
Opened 2023-10-03 20:49 UTC by Winzen

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

Grupo 2 de municípios requisitados na Issue #950. 🥳 
#
Logs:
[log_sp_jau.txt](https://github.com/okfn-brasil/querido-diario/files/12796824/log_sp_jau.txt)
[log_sp_mogi_guacu.txt](https://github.com/okfn-brasil/querido-diario/files/12796825/log_sp_mogi_guacu.txt)
[log_sp_salto.txt](https://github.com/okfn-brasil/querido-diario/files/12796826/log_sp_salto.txt)
[log_sp_sertaozinho.txt](https://github.com/okfn-brasil/querido-diario/files/12796827/log_sp_sertaozinho.txt)
[log_sp_itu.txt](https://github.com/okfn-brasil/querido-diario/files/12796828/log_sp_itu.txt)

**Obs:** Todos os diários estão vindo sem extensão 😞

2023-10-04 17:20 UTC, trevineju commented
boa, @Winzen! 🥳 

Sei que já falamos isso informalmente, mas para ficar registrado:
- O código para Jau que já existia no repo raspa um site que ainda existe e tem até uma série histórica maior, por isso não vamos sobreescrever o arquivo, temos que preservar o raspador anterior. Você pode ajustar isso? Retira as modificações que fez em `sp_jau.py` e aí o raspador que usa DOSP vc coloca em `sp_jau_2023.py`. 
- O raspador para Itu também está sendo modificado, porém nesse caso ele já usava a URL de DOSP, então pode deixar como está no PR (sobreescrevendo o arquivo)

2023-10-04 17:23 UTC, trevineju requested changes
boa, @Winzen! 🥳

Sei que já falamos isso informalmente, mas para ficar registrado:

- O código para Jau que já existia no repo raspa um site que ainda existe e tem até uma série histórica maior, por isso não vamos sobreescrever o arquivo, temos que preservar o raspador anterior. Você pode ajustar isso? Retira as modificações que fez em `sp_jau.py` e aí o código que usa DOSP vc coloca em `sp_jau_2023.py`.
- O raspador para Itu também está sendo modificado, porém nesse caso ele já usava a URL de DOSP, então pode deixar como está no PR (sobreescrevendo o arquivo)

2023-10-04 19:47 UTC, Winzen commented
@trevineju
Na  [lista de spiders habilitados](https://github.com/okfn-brasil/querido-diario/blob/main/scripts/enabled_spiders.py) eu colocaria o `sp_jau_2023`, né? 😕 
Porque o `sp_jau` antigo, precisa de revisão, certo?

2023-10-04 19:47 UTC, trevineju commented
isso!

2023-10-06 12:05 UTC, trevineju approved these changes
<img src="https://media4.giphy.com/media/1q9addeaZMx020Gv8u/giphy.gif"/>

2023-10-06 12:07 UTC, trevineju commented
a modificação que fiz foi mais organizacional: juntei todos os commits em um só, no primeiro.

2023-10-06 12:07 UTC, merged