Issue #907
okfn-brasil/querido-diario pull request #956
Opened 2023-10-03 22:45 UTC by victorfernandesraton

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [ x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [ x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [ x] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [ x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [ ] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

<Descreva o seu Pull Request informando a issue (caso exista) que está sendo solucionada ou uma descrição do código apresentado>

2023-10-09 23:40 UTC, rennerocha requested changes
Adicionei alguns comentários e sugestões nesse PR.

2023-10-09 23:40 UTC, rennerocha commented on data_collection/gazette/spiders/base/sai.py
> +            url=self.get_url(),
**sugestão** Substitua a chamada do método pela string e remova o método `get_url()`. O uso indiscriminado de funções tão pequenas e sem nenhuma lógica especial torna o código mais difícil de ler e acompanhar, pois você precisa mudar de contexto na sua cabeça para descobrir o que está acontecendo.

```
        yield scrapy.FormRequest(
            formdata=formdata,
            url=f"{self.base_url}/{self.state_city_url_part}/Site/DiarioOficial",
            callback=self.parse_item,
        )

```

2023-10-09 23:40 UTC, rennerocha commented on data_collection/gazette/spiders/base/sai.py
> +        This is a POST request to get page with all data unitl now
**sugestão** O docstring não está acrescentando nenhuma informação que não é possível obter apenas lendo o código. Pode ser removido sem problemas.

2023-10-09 23:40 UTC, rennerocha commented on data_collection/gazette/spiders/base/sai.py
> +    Base Spyder for all cases with use SAI (Serviço de Acesso a Informação)
**typo** É spider, e não spyder

2023-10-09 23:40 UTC, rennerocha commented on data_collection/gazette/spiders/base/sai.py
> +        This is a method to run each row in table and get streuctured information
**sugestão** O docstring não está acrescentando nenhuma informação que não é possível obter apenas lendo o código. Pode ser removido sem problemas.

2023-10-09 23:40 UTC, rennerocha commented on data_collection/gazette/spiders/base/sai.py
> +        gazette_list = json.loads(response.body)
**sugestão** Se o response é do tipo JSON, você pode substituir essa linha por:
```
gazettes = response.json()
```

2023-10-09 23:40 UTC, rennerocha commented on data_collection/gazette/spiders/base/sai.py
> +            date = self.get_date(gazette_item["dat_criacao"])
**sugestão** Novamente não vejo benefícios em introduzir uma troca de contexto (chamar um método), para fazer uma ação de uma linha. Você pode remover `get_date e `get_file_url` e colocar o conteúdo desses métodos aqui sem problemas. Fazendo isso, quem estiver lendo o código no futuro, poderá fazé-lo sem precisar se movimentar pelo arquivo e continuar entendendo perfeitamente o que está acontecendo.

2023-10-10 01:18 UTC, victorfernandesraton commented on data_collection/gazette/spiders/base/sai.py
> +            url=self.get_url(),
Correçcão feita em https://github.com/okfn-brasil/querido-diario/pull/956/commits/5c11715926b5bedffe46876d56ea132a0ee7ac2f

2023-10-10 01:19 UTC, victorfernandesraton commented on data_collection/gazette/spiders/base/sai.py
> +        This is a POST request to get page with all data unitl now
Correção feirta em https://github.com/okfn-brasil/querido-diario/pull/956/commits/5c11715926b5bedffe46876d56ea132a0ee7ac2f

2023-10-10 01:19 UTC, victorfernandesraton commented on data_collection/gazette/spiders/base/sai.py
> +    Base Spyder for all cases with use SAI (Serviço de Acesso a Informação)
Correção feita em

2023-10-10 01:19 UTC, victorfernandesraton commented on data_collection/gazette/spiders/base/sai.py
> +        This is a method to run each row in table and get streuctured information
Correção feita em https://github.com/okfn-brasil/querido-diario/pull/956/commits/5c11715926b5bedffe46876d56ea132a0ee7ac2f

2023-10-10 01:19 UTC, victorfernandesraton commented on data_collection/gazette/spiders/base/sai.py
> +        gazette_list = json.loads(response.body)
Correçãp feita em https://github.com/okfn-brasil/querido-diario/pull/956/commits/5c11715926b5bedffe46876d56ea132a0ee7ac2f

2023-10-10 01:20 UTC, victorfernandesraton commented on data_collection/gazette/spiders/base/sai.py
> +            date = self.get_date(gazette_item["dat_criacao"])
Correção feit aem https://github.com/okfn-brasil/querido-diario/pull/956/commits/5c11715926b5bedffe46876d56ea132a0ee7ac2f

2023-10-10 12:52 UTC, trevineju commented on data_collection/gazette/spiders/ba/ba_maragogipe.py
> +class BaMaragogipeSpider(SaiGazeteSpider):
```suggestion
from gazette.spiders.base.sai import SaiGazetteSpider


class BaMaragogipeSpider(SaiGazetteSpider):
```

Corrige typo

2023-10-10 12:56 UTC, trevineju commented on data_collection/gazette/spiders/ba/ba_maragogipe.py
> +    start_date = dt.date(2023, 1, 1)
```suggestion
    start_date = dt.date(2011, 2, 2)
```
A página tem um filtro por ano que vai até 2011. Não começa em 2023.

2023-10-10 22:41 UTC, victorfernandesraton commented on data_collection/gazette/spiders/ba/ba_maragogipe.py
> +    name = "ba_maragojipe"
Porém a url n funciona com maragogipe por algum motivo

2023-10-10 23:25 UTC, victorfernandesraton commented
Execução de todo o período
[ba_maragogipe_all.csv](https://github.com/okfn-brasil/querido-diario/files/12862750/ba_maragogipe_all.csv)
[ba_maragogipe_all.log](https://github.com/okfn-brasil/querido-diario/files/12862751/ba_maragogipe_all.log)

2023-10-11 00:13 UTC, victorfernandesraton commented
Execução de data aleatória
[ba_maragogipe_2021.csv](https://github.com/okfn-brasil/querido-diario/files/12862960/ba_maragogipe_2021.csv)
[ba_maragogipe_2021.log](https://github.com/okfn-brasil/querido-diario/files/12862961/ba_maragogipe_2021.log)

2023-10-17 13:34 UTC, trevineju requested changes
Obrigada por encaminhar os ajustes, @victorfernandesraton. 😃  

Acredito que ainda precise melhorar as questões com a URL. Por exemplo, são todos sites de SAI: 
https://sai.io.org.br/ba/laurodefreitas/Site/DiarioOficial
https://www.estancia.se.gov.br/Site/DiarioOficial
https://www.igaci.al.gov.br/Site/DiarioOficial

No ponto em que a PR está, apenas os casos de páginas no domínio `sai.io.org.br` seriam válidos. Precisa deixar a solução um pouco mais genérica para incluir esses casos também (talvez deixando um atributo de classe `url` nas classes filhas e não no spider base?)

Com essa alteração, poderia vir outra. O atributo `client_id` está um tanto hardcoded, o que não é exatamente um problema nesse tipo de situação, mas se formos adicionar a url dentro de cada spider de município, talvez coletar o `client_id` possa passar a ser um método de `sai.py`. Conferi aqui para esses casos listados acima que o xpath `//select[@id="cod_cliente"]/option[2]` pega o `client_id` (talvez esse xpath pode ser melhorado, mas queria só um exemplo rápido)

2023-10-17 22:04 UTC, victorfernandesraton commented
> //select[@id="cod_cliente"]

Boa sendo bem sincero n tinha innvesticado a questao do code ainda, mas vou correr aqui atrás disso, por hora vou deixar em draft.

Valéu ai pelas dicas

2023-10-30 00:23 UTC, victorfernandesraton commented
Evidências finais

[al_igaci-all.csv](https://github.com/okfn-brasil/querido-diario/files/13199631/al_igaci-all.csv)
[al_igaci-all.log](https://github.com/okfn-brasil/querido-diario/files/13199632/al_igaci-all.log)
[al_igaci-range.csv](https://github.com/okfn-brasil/querido-diario/files/13199633/al_igaci-range.csv)
[al_igaci-range.log](https://github.com/okfn-brasil/querido-diario/files/13199634/al_igaci-range.log)
[ba_lauro_de_freitas-all.csv](https://github.com/okfn-brasil/querido-diario/files/13199635/ba_lauro_de_freitas-all.csv)
[ba_lauro_de_freitas-all.log](https://github.com/okfn-brasil/querido-diario/files/13199636/ba_lauro_de_freitas-all.log)
[ba_lauro_de_freitas-range.csv](https://github.com/okfn-brasil/querido-diario/files/13199637/ba_lauro_de_freitas-range.csv)
[ba_lauro_de_freitas-range.log](https://github.com/okfn-brasil/querido-diario/files/13199638/ba_lauro_de_freitas-range.log)
[ba_maragogipe-all.csv](https://github.com/okfn-brasil/querido-diario/files/13199639/ba_maragogipe-all.csv)
[ba_maragogipe-all.log](https://github.com/okfn-brasil/querido-diario/files/13199640/ba_maragogipe-all.log)
[ba_maragogipe-range.csv](https://github.com/okfn-brasil/querido-diario/files/13199641/ba_maragogipe-range.csv)
[ba_maragogipe-range.log](https://github.com/okfn-brasil/querido-diario/files/13199642/ba_maragogipe-range.log)
[se_estancia-all.csv](https://github.com/okfn-brasil/querido-diario/files/13199643/se_estancia-all.csv)
[se_estancia-all.log](https://github.com/okfn-brasil/querido-diario/files/13199644/se_estancia-all.log)
[se_estancia-range.csv](https://github.com/okfn-brasil/querido-diario/files/13199645/se_estancia-range.csv)
[se_estancia-range.log](https://github.com/okfn-brasil/querido-diario/files/13199646/se_estancia-range.log)

2024-03-20 22:30 UTC, ogecece approved these changes
@victorfernandesraton PR revisado e pronto pra integrar! Aproveitei pra adicionar alguns municípios pertencentes ao Matopiba, região que vai ser utilizada para algumas reportagens.

![baile](https://github.com/okfn-brasil/querido-diario/assets/26327506/23edb92e-04a4-4355-8e91-a00f9e6e6b0f)

Ainda eram necessárias algumas mudanças. Coloquei na descrição do commit 4d69e84. Se tiver alguma dúvida pode perguntar à vontade. Mas no geral achei a implementação ficou boa, os padrões e regras do projeto a gente pega com o tempo.

Deixo aqui os logs dos 4 municípios adicionados (o range de correntina foi 2020-05-15 a 2020-07-02):
[ba_correntina-range.csv](https://github.com/okfn-brasil/querido-diario/files/14673145/ba_correntina-range.csv)
[ba_correntina-range.log](https://github.com/okfn-brasil/querido-diario/files/14673146/ba_correntina-range.log)
[ba_correntina-all.log](https://github.com/okfn-brasil/querido-diario/files/14673148/ba_correntina-all.log)
[ba_correntina-all.csv](https://github.com/okfn-brasil/querido-diario/files/14673149/ba_correntina-all.csv)
[ba_jaborandi-all.log](https://github.com/okfn-brasil/querido-diario/files/14673150/ba_jaborandi-all.log)
[ba_jaborandi-all.csv](https://github.com/okfn-brasil/querido-diario/files/14673151/ba_jaborandi-all.csv)
[ba_lem-all.csv](https://github.com/okfn-brasil/querido-diario/files/14673152/ba_lem-all.csv)
[ba_lem-all.log](https://github.com/okfn-brasil/querido-diario/files/14673153/ba_lem-all.log)
[ba_rdn-all.csv](https://github.com/okfn-brasil/querido-diario/files/14673154/ba_rdn-all.csv)
[ba_rdn-all.log](https://github.com/okfn-brasil/querido-diario/files/14673155/ba_rdn-all.log)

2024-03-20 22:31 UTC, ogecece commented
Ah! Também fiz squash nos commits pra deixar a história mais organizada.

2024-03-20 22:33 UTC, merged