Raspadores de DOEM - Antônio Cardoso - BA
okfn-brasil/querido-diario pull request #964
Opened 2023-10-09 20:36 UTC by natanluiz99

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [ ] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [ ] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [ ] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [ ] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [ ] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

#947

Arquivos com Logs da checagem geral (scrapy crawl ba_antonio_cardoso -s LOG_FILE=ba_antonio_cardoso.txt -o 
 ba_antonio_cardoso.csv)
[ba_antonio_cardoso.csv](https://github.com/okfn-brasil/querido-diario/files/12850410/ba_antonio_cardoso.csv)
[ba_antonio_cardoso.txt](https://github.com/okfn-brasil/querido-diario/files/12850412/ba_antonio_cardoso.txt)

Arquivos com Logs da checagem aleatória com start_date e end_date (2019-09-01 a 2019-11-01)
[ba_antonio_cardoso_2019(09-11).txt](https://github.com/okfn-brasil/querido-diario/files/12850430/ba_antonio_cardoso_2019.09-11.txt)
[ba_antonio_cardoso2019.csv](https://github.com/okfn-brasil/querido-diario/files/12850431/ba_antonio_cardoso2019.csv)

Em ambos os Logs não foram encontrados erros sequer, além dos dados extraídos estarem de acordo com o escopo esperado.

Spider modificado com atributo de classe para o primeiro dia de publicação dos diários (2018-01-03)

2023-10-09 20:40 UTC, natanluiz99 commented
#947 
Arquivos com Logs da checagem geral (scrapy crawl ba_alcobaca -s LOG_FILE=ba_alcobaca.txt -o [ba_alcobaca.csv](https://github.com/okfn-brasil/querido-diario/files/12850357/ba_alcobaca.csv))
ba_alcobaca.csv
[ba_alcobaca.txt](https://github.com/okfn-brasil/querido-diario/files/12849880/ba_alcobaca.txt)

Arquivos com Logs da checagem aleatória com start_date e end_date (2022-06-01 a 2022-08-01)
[ba_alcobaca2022.csv](https://github.com/okfn-brasil/querido-diario/files/12850312/ba_alcobaca2022.csv)
[ba_alcobaca_2022(06-08).txt](https://github.com/okfn-brasil/querido-diario/files/12849885/ba_alcobaca_2022.06-08.txt)

Em ambos os Logs não foram encontrados erros sequer, além dos dados extraídos estarem de acordo com o escopo esperado.

Spider modificado com atributo de classe para o primeiro dia de publicação dos diários (2018-01-02)

2023-10-09 21:05 UTC, natanluiz99 commented
**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

#947

Arquivos com Logs da checagem geral (scrapy crawl ba_banzae -s LOG_FILE=ba_banzae.txt -o 
 ba_banzae.csv)
[ba_banzae.txt](https://github.com/okfn-brasil/querido-diario/files/12850629/ba_banzae.txt)
[ba_banzae.csv](https://github.com/okfn-brasil/querido-diario/files/12850631/ba_banzae.csv)



Arquivos com Logs da checagem aleatória com start_date e end_date (2018-04-01 a 2018-06-01)
[ba_banzae_2018(04-06).txt](https://github.com/okfn-brasil/querido-diario/files/12850632/ba_banzae_2018.04-06.txt)
[ba_banzae2018.csv](https://github.com/okfn-brasil/querido-diario/files/12850633/ba_banzae2018.csv)



Em ambos os Logs não foram encontrados erros sequer, além dos dados extraídos estarem de acordo com o escopo esperado.

Spider modificado com atributo de classe para o primeiro dia de publicação dos diários (2017-02-02)

2023-10-10 23:34 UTC, natanluiz99 commented
**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_cou
[ba_barra_do_choca.csv](https://github.com/okfn-brasil/querido-diario/files/12862790/ba_barra_do_choca.csv)
nt/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

#947

Arquivos com Logs da checagem geral (scrapy crawl ba_barra_do_choca -s LOG_FILE=ba_barra_do_choca.txt -o 
 ba_barra_do_choca.csv)

[ba_barra_do_choca.txt](https://github.com/okfn-brasil/querido-diario/files/12862789/ba_barra_do_choca.txt)
[ba_barra_do_choca.csv](https://github.com/okfn-brasil/querido-diario/files/12862793/ba_barra_do_choca.csv)



Arquivos com Logs da checagem aleatória com start_date e end_date (2020-07-01 a 2020-09-01)
[ba_barra_do_choca_2020(07-09).txt](https://github.com/okfn-brasil/querido-diario/files/12862786/ba_barra_do_choca_2020.07-09.txt)
[ba_barra_do_choca2020.csv](https://github.com/okfn-brasil/querido-diario/files/12862787/ba_barra_do_choca2020.csv)




Em ambos os Logs não foram encontrados erros sequer, além dos dados extraídos estarem de acordo com o escopo esperado.

Spider modificado com atributo de classe para o primeiro dia de publicação dos diários (2018-01-02)

2023-10-12 01:25 UTC, natanluiz99 commented
encontrei uma inconsistência na extração do ba_barrocas, estou checando a extração dos dados utilizando o site do doem para comparar com os dados extraídos, dessa forma percebi a diferença entre edições por exemplo no mesmo dia do link extraído do doem e o outro do raspador e verifiquei mais afundo para tentar descobrir de onde estaria vindo esse outro diario que o raspador está pegando
DOEM Site da cidade
![image](https://github.com/okfn-brasil/querido-diario/assets/34273197/bf4db09e-27be-4661-b766-5f392b697cd0)
DOEM extraído do raspador 
![image](https://github.com/okfn-brasil/querido-diario/assets/34273197/6b1e181e-943c-4247-ac68-748a3835a572)

2023-10-16 22:42 UTC, trevineju requested changes
Ajustes: 
- [ ] A biblioteca `date` está sendo usada em todos os raspadores (linha 8, sempre), porém não está sendo importada. É necessário adicionar `from datetime import date` em todos os arquivos
- [ ] Adicionar `_2017` no nome do arquivo e no atributo de classe `name` (linha 6) para Antonio Cardoso, Barra do Choça e Barrocas
- Sei que nem enviou Barrocas ainda, mas já olhei o site também.
> Motivo: Estamos adotando que quando um site migra, adicionamos o ano inicial. Exemplo: [PE_Recife](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/pe). Note que tem dois, pq um raspador raspa certo site (a partir de 2015) e passa a raspar outro (a partir de 2022). É o mesmo caso aqui, já sabemos que o site mudou já que nesses 3 casos, não tem diários de hoje (outubro/2023)

2023-10-16 22:48 UTC, trevineju commented on data_collection/gazette/spiders/ba/ba_antonio_cardoso.py
> +    start_date = date(2018, 1, 3)
```suggestion
    start_date = date(2017, 1, 2)
```
Sei que no botão do site aparece só até 2018, porém se vc explorar a URL (https://doem.org.br/ba/antoniocardoso/diarios/{ANO}/) vai ver que abre pra mais diários! ;) 

https://doem.org.br/ba/antoniocardoso/diarios/2017/1

2023-10-16 22:53 UTC, trevineju commented on data_collection/gazette/spiders/ba/ba_barra_do_choca.py
> +    start_date = date(2018, 1, 2)
```suggestion
    start_date = date(2017, 6, 9)
```

2023-10-16 23:16 UTC, trevineju commented
> encontrei uma inconsistência na extração do ba_barrocas

Não consegui achar esses dois casos. Só um: https://doem.org.br/ba/barrocas/diarios/2018/1
Mas de qualquer forma, me parece uma inconsistência interna ao arquivo (ou seja, a pessoa que foi formatar o PDF editou errado). Como os raspadores raspam o site, não teria problema.

2023-10-16 23:36 UTC, trevineju commented
Os mesmos ajustes comentados aqui servem também pra PR #963 (adicionar o import, corrigir a data inicial e mudar o nome do arquivo)

2023-10-17 00:24 UTC, natanluiz99 commented
> Ajustes:
> 
> * [ ]  A biblioteca `date` está sendo usada em todos os raspadores (linha 8, sempre), porém não está sendo importada. É necessário adicionar `from datetime import date` em todos os arquivos
> * [ ]  Adicionar `_2017` no nome do arquivo e no atributo de classe `name` (linha 6) para Antonio Cardoso, Barra do Choça e Barrocas
> * Sei que nem enviou Barrocas ainda, mas já olhei o site também.
> 
> > Motivo: Estamos adotando que quando um site migra, adicionamos o ano inicial. Exemplo: [PE_Recife](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/pe). Note que tem dois, pq um raspador raspa certo site (a partir de 2015) e passa a raspar outro (a partir de 2022). É o mesmo caso aqui, já sabemos que o site mudou já que nesses 3 casos, não tem diários de hoje (outubro/2023)

Irei fazer as devidas modificações e vou experimentar nas próximas vezes explorar pela URL também.
 
>Não consegui achar esses dois casos. Só um: https://doem.org.br/ba/barrocas/diarios/2018/1
>Mas de qualquer forma, me parece uma inconsistência interna ao arquivo (ou seja, a pessoa que foi formatar o PDF editou errado). Como os raspadores raspam o site, não teria problema.

vou colocar o link de ambos, mas como nesse caso o problema é a formatação deles, vou focar em outra situação.

2023-10-17 00:46 UTC, natanluiz99 commented
**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_cou
[ba_barra_do_choca.csv](https://github.com/okfn-brasil/querido-diario/files/12862790/ba_barra_do_choca.csv)
nt/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

#947

Arquivos com Logs da checagem geral (scrapy crawl ba_barrocas -s LOG_FILE=ba_barrocas.txt -o 
 ba_barroca.csv)

[ba_barrocas.csv](https://github.com/okfn-brasil/querido-diario/files/12923101/ba_barrocas.csv)
[ba_barrocas.txt](https://github.com/okfn-brasil/querido-diario/files/12923102/ba_barrocas.txt)




Arquivos com Logs da checagem aleatória com start_date e end_date (2021-01-01 a 2021-03-01)
[ba_barrocas2021(01-03).txt](https://github.com/okfn-brasil/querido-diario/files/12923098/ba_barrocas2021.01-03.txt)
[ba_barrocas2021.csv](https://github.com/okfn-brasil/querido-diario/files/12923099/ba_barrocas2021.csv)





Em ambos os Logs não foram encontrados erros sequer, além dos dados extraídos estarem de acordo com o escopo esperado.

Spider modificado com atributo de classe para o primeiro dia de publicação dos diários (2017-01-02)

2023-10-17 01:03 UTC, natanluiz99 commented
> Ajustes:
> 
> * [ ]  A biblioteca `date` está sendo usada em todos os raspadores (linha 8, sempre), porém não está sendo importada. É necessário adicionar `from datetime import date` em todos os arquivos
> * [ ]  Adicionar `_2017` no nome do arquivo e no atributo de classe `name` (linha 6) para Antonio Cardoso, Barra do Choça e Barrocas
> * Sei que nem enviou Barrocas ainda, mas já olhei o site também.
> 
> > Motivo: Estamos adotando que quando um site migra, adicionamos o ano inicial. Exemplo: [PE_Recife](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/pe). Note que tem dois, pq um raspador raspa certo site (a partir de 2015) e passa a raspar outro (a partir de 2022). É o mesmo caso aqui, já sabemos que o site mudou já que nesses 3 casos, não tem diários de hoje (outubro/2023)

alterações feitas nesses 3 spiders, atributo de classe name, nome do arquivo .py
será necessário fazer isso para Alcobaça e Banzaé ?

2023-10-17 14:07 UTC, trevineju commented
> alterações feitas nesses 3 spiders, atributo de classe name, nome do arquivo .py será necessário fazer isso para Alcobaça e Banzaé ?

Boa! Obrigada! 
Banzaé não precisa. Nós só usamos esse artifício de colocar `uf_municipio_ano` para diferenciar dois arquivos. No caso de Banzaé não teremos um segundo arquivo (até o momento, pelo menos), pq o município segue usando o DOEM como sistema (é o local de publicação de diários vigente). Mas Alcobaça sim.  

Porém, Alcobaça está nessa PR e em outra PR (a #963). Vc poderia escolher deixar ou lá ou aqui. Precisa da modificação de qualquer maneira, mas pode ser feita em apenas um lugar.

2023-10-17 14:15 UTC, natanluiz99 commented
> > alterações feitas nesses 3 spiders, atributo de classe name, nome do arquivo .py será necessário fazer isso para Alcobaça e Banzaé ?
> 
> Boa! Obrigada! Banzaé não precisa. Nós só usamos esse artifício de colocar `uf_municipio_ano` para diferenciar dois arquivos. No caso de Banzaé não teremos um segundo arquivo (até o momento, pelo menos), pq o município segue usando o DOEM como sistema (é o local de publicação de diários vigente). Mas Alcobaça sim.
> 
> Porém, Alcobaça está nessa PR e em outra PR (a #963). Vc poderia escolher deixar ou lá ou aqui. Precisa da modificação de qualquer maneira, mas pode ser feita em apenas um lugar.

Fiz as devidas alterações agora na Alcobaça BA, preferi continuar nessa PR as alterações de todas as cidades

2023-10-17 14:37 UTC, trevineju commented
Boa, @natanluiz99! 

Fiz algumas modificações: 
1. Juntei todos aqueles seus commits em um só, mais para a história de modificações do repositório ficarem organizadas: https://github.com/okfn-brasil/querido-diario/pull/964/commits/13646c54e9b527d3b44ee3137d827df21f5d2030
2. Adicionei um commit habilitando a cidade de Banzaé em produção!! 🎉 : https://github.com/okfn-brasil/querido-diario/pull/964/commits/a9e61f6a485a729ad932b0f907bf16130fd4c39e
3. E precisei rodar uma rotina de correção da formação do código: https://github.com/okfn-brasil/querido-diario/pull/964/commits/557a4ad5ac1268cddd47a07804426cfd70d346a9
Nesse caso, isso indica que na sua máquina o `pre-commit` não está instalado devidamente. Saiba mais em: [Formatação Automática de Código](https://github.com/okfn-brasil/querido-diario/blob/main/docs/CONTRIBUTING.md#forma%C3%A7%C3%A3o-autom%C3%A1tica-de-c%C3%B3digo)

2023-10-17 14:38 UTC, trevineju approved these changes
Obrigada pela contribuição! 
<img src="https://media0.giphy.com/media/YJ5OlVLZ2QNl6/giphy.gif"/>

2023-10-17 14:39 UTC, merged