Raspadores de DOEM - Grupo 5
okfn-brasil/querido-diario pull request #966
Opened 2023-10-10 23:45 UTC by OseOliv

**AO ABRIR** um Pull Request de um novo raspador (spider), marque com um `X` cada um dos items do checklist 
abaixo. **NÃO ABRA** um novo Pull Request antes de completar todos os items abaixo.

#### Checklist - Novo spider
- [x] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [x] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [x] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [x] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [x] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

# Grupo 5 Raspadores de DOEM 

- Tabocas do Brejo Velho-BA
- Santa Cruz Cabralia-BA
- Sento Sé-BA
- Teixeira de Freitas-BA
- Santo Amaro-BA
- Ribeira do Pombal-BA

# Logs:

- Tabocas do Brejo Velho-BA
> [ba_tabocas_do_brejo_velho.txt](https://github.com/okfn-brasil/querido-diario/files/12862807/ba_tabocas_do_brejo_velho.txt)
> [ba_tabocas_do_brejo_velho.csv](https://github.com/okfn-brasil/querido-diario/files/12862810/ba_tabocas_do_brejo_velho.csv)

- Santa Cruz Cabralia-BA
> [ba_santa_cruz_cabralia.txt](https://github.com/okfn-brasil/querido-diario/files/12862812/ba_santa_cruz_cabralia.txt)
> [ba_santa_cruz_cabralia.csv](https://github.com/okfn-brasil/querido-diario/files/12862814/ba_santa_cruz_cabralia.csv)

- Sento Sé-BA
> [ba_sento_se.txt](https://github.com/okfn-brasil/querido-diario/files/12862820/ba_sento_se.txt)
> [ba_sento_se.csv](https://github.com/okfn-brasil/querido-diario/files/12862821/ba_sento_se.csv)

- Teixeira de Freitas-BA
> [ba_teixeira_de_freitas.txt](https://github.com/okfn-brasil/querido-diario/files/12862824/ba_teixeira_de_freitas.txt)
> [ba_teixeira_de_freitas.csv](https://github.com/okfn-brasil/querido-diario/files/12862825/ba_teixeira_de_freitas.csv)

- Santo Amaro-BA
> [ba_santo_amaro.txt](https://github.com/okfn-brasil/querido-diario/files/12862828/ba_santo_amaro.txt)
> [ba_santo_amaro.csv](https://github.com/okfn-brasil/querido-diario/files/12862829/ba_santo_amaro.csv)

- Ribeira do Pombal-BA
> [ba_ribeira_do_pombal.csv](https://github.com/okfn-brasil/querido-diario/files/12862834/ba_ribeira_do_pombal.csv)
> [ba_ribeira_do_pombal.txt](https://github.com/okfn-brasil/querido-diario/files/12862833/ba_ribeira_do_pombal.txt)

.espero que seja isso.

2023-10-17 18:43 UTC, trevineju commented on data_collection/gazette/spiders/ba/ba_ribeira_do_pombal.py
> +    start_date = date(2007, 9, 18)
```suggestion
    start_date = date(2014, 1, 16)
```

2023-10-17 19:13 UTC, trevineju requested changes
Oi, @OseOliv! Obrigada pela PR! 

Adicionei algumas solicitações de ajustes relacionados a corrigir a data inicial. 

Em alguns casos, também pedi pra adicionar um `_ano` no nome do raspador. O motivo disso é que, nesses casos, os municípios não usam mais o site do DOEM para disponibilizar diários. Isso significa que só tem diários a partir de determinada data. Nesses casos, preciso de mais uma alteração: adicionar o `_ano` também no nome do arquivo (ou seja: `ba_teixeira_de_freitas.py` deve passar a ser `ba_teixeira_de_freitas_2021.py`). Pode ajustar isso?

2023-10-17 19:13 UTC, trevineju commented on data_collection/gazette/spiders/ba/ba_teixeira_de_freitas.py
> +    start_date = date(2014, 12, 31)
```suggestion
    start_date = date(2021, 3, 2) 
```

Achado em: https://doem.org.br/ba/teixeiradefreitas/diarios/2021/3

2023-10-17 19:13 UTC, trevineju commented on data_collection/gazette/spiders/ba/ba_teixeira_de_freitas.py
>      name = "ba_teixeira_de_freitas"
```suggestion
    name = "ba_teixeira_de_freitas_2021"
```

2023-10-18 14:18 UTC, OseOliv commented
Alterações foram feitas e os LOGs foram reenviados com as alterações.

2023-10-18 21:17 UTC, trevineju approved these changes
ihuu!! PR aprovada! Obrigada pela contribuição @OseOliv! 

Fiz apenas dois ajustes: 
1. Juntei todos seus commits em um só, para não poluir o histórico do repositório: https://github.com/okfn-brasil/querido-diario/pull/966/commits/f2278af64a6261ea7e6ade118b14c4114c4e4ff1  
2. Adicionei um commit habilitando os raspadores adequados em produção! (até o fim da semana, as cidades que contribuiu estarão no ar 😍 🎉) : https://github.com/okfn-brasil/querido-diario/pull/966/commits/a351595df8f71450094c3d1455a2f995227975d5

<img src="https://media3.giphy.com/media/1BFEEIo4h1BuTH8eqP/giphy.gif"/>

2023-10-18 21:18 UTC, merged