Add cidades instar (Cachoeira do sul-RS, Januaria-MG, Monte Mor-SP)
okfn-brasil/querido-diario pull request #991
Opened 2023-10-23 18:10 UTC by MatmaK

#### Checklist - Novo spider
- [X] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [X] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [X] Você verificou que não existe nenhum erro nos logs (`log_count/ERROR` igual a zero).
- [X] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [X] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).

#### Descrição

Issue #986 
Task 4
Adicionado Spiders das cidades abaixo:
Cachoeira do sul-RS, 
Januaria-MG, 
Monte Mor-SP

2023-10-23 19:57 UTC, trevineju requested changes
@MatmaK está excelente a PR! Adicionei só um ajuste ;)

2023-10-23 19:57 UTC, trevineju commented on data_collection/gazette/spiders/sp/sp_monte_mor.py
> +    start_date = date(2019, 7, 20)
```suggestion
    start_date = date(2019, 9, 20)
```

2023-10-24 12:45 UTC, trevineju commented
@MatmaK você vai enviar as demais cidades aqui nesta PR ainda? Acho que você tinha perdido o fim do workshop, mas abri a issue para serem 4 PRs justamente pra ajudar vocês na Hacktoberfest. Mas se você não fizer questão disso, poderia sim mandar tudo em 1 PR só. 

Pra avisar que as 3 primeiras cidades estão aprovadíssimas 🥳

2023-10-24 12:50 UTC, MatmaK commented
> @MatmaK você vai enviar as demais cidades aqui nesta PR ainda? Acho que você tinha perdido o fim do workshop, mas abri a issue para serem 4 PRs justamente pra ajudar vocês na Hacktoberfest. Mas se você não fizer questão disso, poderia sim mandar tudo em 1 PR só.
> 
> Pra avisar que as 3 primeiras cidades estão aprovadíssimas 🥳

@trevineju ia te perguntar sobre isso, eu fiz o ajuste das outras cidades, mas subi na mesma branch aí quando fui abrir um novo pr meio que vinculou a esse já aberto. Teria que criar uma nova branch pra cada pr?

2023-10-24 13:30 UTC, trevineju commented
se você tiver problemas com algum desses passos, avisa!

2023-10-24 14:38 UTC, MatmaK commented
@trevineju acho que deu certo. Obrigado!

2023-10-24 18:21 UTC, trevineju approved these changes
ficou excelente, @MatmaK! PR revisada e aprovada!! ❤️  Obrigada pela contribuição! 🎉 

habilitei estes novos raspadores em produção, os dados raspados estarão no ar a partir de amanhã 

<img src="https://media3.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif"/>

2023-10-24 18:23 UTC, merged